/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.solid.analytics.model;

import java.util.Hashtable;
import java.util.Iterator;
import java.util.Vector;
import java.util.Enumeration;

import org.json.*;

import com.solid.analytics.thrift.*;
import com.solid.analytics.thrift.meta_data.*;
import com.solid.analytics.thrift.transport.*;
import com.solid.analytics.thrift.protocol.*;

public class ActivedRequest implements TBase {
  private static final TStruct STRUCT_DESC = new TStruct("");

  private static final TField PUB_ID_FIELD_DESC = new TField("E3E819E676A853BA8A7BB448994814DD", TType.STRING, (short)1);
  private static final TField PKGNAME_FIELD_DESC = new TField("247E7A404DC9865E209ABF7FC9736806", TType.STRING, (short)2);
  private static final TField REGION_FIELD_DESC = new TField("5344EB562E926ACBF4C050FFEB2CB658", TType.STRING, (short)3);
  private static final TField COUNTRY_FIELD_DESC = new TField("A53894C8998E21DB94C9264B882B10F4", TType.STRING, (short)4);
  private static final TField TIMEZONE_FIELD_DESC = new TField("C8E8C3EA6511C464A224CD9CBBABCB7B", TType.STRING, (short)5);
  private static final TField CARRIER_FIELD_DESC = new TField("ABC0A71EBFFC08C3469350E4C6C21FD7", TType.STRING, (short)6);
  private static final TField LONGITUDE_FIELD_DESC = new TField("D5BAE9541F130C2DA32CF601DC64119E", TType.DOUBLE, (short)7);
  private static final TField LATITUDE_FIELD_DESC = new TField("DF466231163DF5342B1B4CE98594D698", TType.DOUBLE, (short)8);
  private static final TField FACEBOOK_FIELD_DESC = new TField("4DEC0B68823C14DCB5C3096E23D12C64", TType.I32, (short)9);
  private static final TField GPSERVICE_FIELD_DESC = new TField("52CA73E7842E354EB7A04607E633A0FD", TType.I32, (short)10);
  private static final TField LANGUAGE_FIELD_DESC = new TField("12AAF5410C9C880A3CA99B343869917B", TType.STRING, (short)11);
  private static final TField MODEL_FIELD_DESC = new TField("ABDDF3E1647BE7F3A8AE2433A70E06D7", TType.STRING, (short)12);
  private static final TField OS_FIELD_DESC = new TField("914EF92BFD5CB7BF6C1030E73EDE9FF4", TType.STRING, (short)13);
  private static final TField OS_VER_FIELD_DESC = new TField("509F19FA575CC1C56C045DCA96F7E20C", TType.STRING, (short)14);
  private static final TField APP_VER_FIELD_DESC = new TField("77CA1148E5F74940EC106A32DC1D5BF5", TType.STRING, (short)15);
  private static final TField ANDROID_ID_FIELD_DESC = new TField("DAB0432BB529DC1F76C440777C86D232", TType.STRING, (short)16);
  private static final TField GAID_FIELD_DESC = new TField("14A948537488C8020631E254C453125F", TType.STRING, (short)17);
  private static final TField IDFA_FIELD_DESC = new TField("BB30A9CAF941935593088670DDBB2E8F", TType.STRING, (short)18);
  private static final TField IMSI_FIELD_DESC = new TField("3447CA69ECC65C251FF41241E62BBD39", TType.STRING, (short)19);
  private static final TField IMEI_FIELD_DESC = new TField("151D281A624318CDE9DCAAD88E8BB381", TType.STRING, (short)20);
  private static final TField IMEI2_FIELD_DESC = new TField("0D59D4C57326F8B1A562646845F9A364", TType.STRING, (short)21);
  private static final TField MAC_FIELD_DESC = new TField("844F6BC9665F82CC489D3859E1101898", TType.STRING, (short)22);
  private static final TField MACSHA1_FIELD_DESC = new TField("17223CD39B7C3BDCA5201D7618129781", TType.STRING, (short)23);
  private static final TField MACMD5_FIELD_DESC = new TField("9BC99CB2E67BA0E0CC5AFE9F14517B1A", TType.STRING, (short)24);
  private static final TField UTM_SOURCE_FIELD_DESC = new TField("FAF1014B76609782A3DC593E3450772E", TType.STRING, (short)25);
  private static final TField UTM_TERM_FIELD_DESC = new TField("309CDE7010D27275708704149F5DE7FA", TType.STRING, (short)26);
  private static final TField UTM_MEDIUM_FIELD_DESC = new TField("9D464E3DB8ACAA4B404A6238057EF748", TType.STRING, (short)27);
  private static final TField UTM_CONTENT_FIELD_DESC = new TField("7E6079E8A2D37C90EB89A29C665BC91D", TType.STRING, (short)28);
  private static final TField UTM_CAMPAIGN_FIELD_DESC = new TField("A03420BF91AE5D2ED2C3512CDD5CD5B0", TType.STRING, (short)29);
  private static final TField EXT1_FIELD_DESC = new TField("0E1671C2682B2691F12ECE4938F0CB25", TType.STRING, (short)30);
  private static final TField EXT2_FIELD_DESC = new TField("4980F2477537812C02009A42E9E97277", TType.STRING, (short)31);
  private static final TField EXT3_FIELD_DESC = new TField("0309E08FF56077B51865563BDEE5055A", TType.STRING, (short)32);
  private static final TField EXT4_FIELD_DESC = new TField("E55ECDA483BA9E3ADE54467196ABCA0D", TType.STRING, (short)33);
  private static final TField EXT5_FIELD_DESC = new TField("18A8D1D5A49169737E58890C0214CE90", TType.STRING, (short)34);
  private static final TField INSTALL_DATE_FIELD_DESC = new TField("D03A5E6310E8B6443C6C457E285FE003", TType.STRING, (short)35);
  private static final TField SERIAL_FIELD_DESC = new TField("1581BABBFDD04AAF281EEE0DF33200F1", TType.STRING, (short)36);
  private static final TField BID_FIELD_DESC = new TField("ABA758D24BA9012D13123C8970E2DF1B", TType.I32, (short)37);
  private static final TField REFERRER_FIELD_DESC = new TField("7934D1A8F2CB3B1D6E3263DA5A91AA8C", TType.STRING, (short)38);

  private String pub_id;
  private String pkgname;
  private String region;
  private String country;
  private String timezone;
  private String carrier;
  private double longitude;
  private double latitude;
  private int facebook;
  private int gpservice;
  private String language;
  private String model;
  private String os;
  private String os_ver;
  private String app_ver;
  private String android_id;
  private String gaid;
  private String idfa;
  private String imsi;
  private String imei;
  private String imei2;
  private String mac;
  private String macsha1;
  private String macmd5;
  private String utm_source;
  private String utm_term;
  private String utm_medium;
  private String utm_content;
  private String utm_campaign;
  private String ext1;
  private String ext2;
  private String ext3;
  private String ext4;
  private String ext5;
  private String install_date;
  private String serial;
  private int bid;
  private String referrer;

  // isset id assignments
  private static final int __LONGITUDE_ISSET_ID = 0;
  private static final int __LATITUDE_ISSET_ID = 1;
  private static final int __FACEBOOK_ISSET_ID = 2;
  private static final int __GPSERVICE_ISSET_ID = 3;
  private static final int __BID_ISSET_ID = 4;
  private boolean[] __isset_vector = new boolean[5];

  public ActivedRequest() {
  }

  public ActivedRequest(
    String pub_id,
    String pkgname,
    String region,
    String country,
    String timezone,
    String carrier,
    double longitude,
    double latitude,
    int facebook,
    int gpservice,
    String language,
    String model,
    String os,
    String os_ver,
    String app_ver,
    String android_id,
    String gaid,
    String idfa,
    String imsi,
    String imei,
    String imei2,
    String mac,
    String macsha1,
    String macmd5,
    String utm_source,
    String utm_term,
    String utm_medium,
    String utm_content,
    String utm_campaign,
    String ext1,
    String ext2,
    String ext3,
    String ext4,
    String ext5,
    String install_date,
    String serial,
    int bid,
    String referrer)
  {
    this();
    this.pub_id = pub_id;
    this.pkgname = pkgname;
    this.region = region;
    this.country = country;
    this.timezone = timezone;
    this.carrier = carrier;
    this.longitude = longitude;
    setLongitudeIsSet(true);
    this.latitude = latitude;
    setLatitudeIsSet(true);
    this.facebook = facebook;
    setFacebookIsSet(true);
    this.gpservice = gpservice;
    setGpserviceIsSet(true);
    this.language = language;
    this.model = model;
    this.os = os;
    this.os_ver = os_ver;
    this.app_ver = app_ver;
    this.android_id = android_id;
    this.gaid = gaid;
    this.idfa = idfa;
    this.imsi = imsi;
    this.imei = imei;
    this.imei2 = imei2;
    this.mac = mac;
    this.macsha1 = macsha1;
    this.macmd5 = macmd5;
    this.utm_source = utm_source;
    this.utm_term = utm_term;
    this.utm_medium = utm_medium;
    this.utm_content = utm_content;
    this.utm_campaign = utm_campaign;
    this.ext1 = ext1;
    this.ext2 = ext2;
    this.ext3 = ext3;
    this.ext4 = ext4;
    this.ext5 = ext5;
    this.install_date = install_date;
    this.serial = serial;
    this.bid = bid;
    setBidIsSet(true);
    this.referrer = referrer;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ActivedRequest(ActivedRequest other) {
    System.arraycopy(other.__isset_vector, 0, __isset_vector, 0, other.__isset_vector.length);
    if (other.isSetPub_id()) {
      this.pub_id = other.pub_id;
    }
    if (other.isSetPkgname()) {
      this.pkgname = other.pkgname;
    }
    if (other.isSetRegion()) {
      this.region = other.region;
    }
    if (other.isSetCountry()) {
      this.country = other.country;
    }
    if (other.isSetTimezone()) {
      this.timezone = other.timezone;
    }
    if (other.isSetCarrier()) {
      this.carrier = other.carrier;
    }
    this.longitude = other.longitude;
    this.latitude = other.latitude;
    this.facebook = other.facebook;
    this.gpservice = other.gpservice;
    if (other.isSetLanguage()) {
      this.language = other.language;
    }
    if (other.isSetModel()) {
      this.model = other.model;
    }
    if (other.isSetOs()) {
      this.os = other.os;
    }
    if (other.isSetOs_ver()) {
      this.os_ver = other.os_ver;
    }
    if (other.isSetApp_ver()) {
      this.app_ver = other.app_ver;
    }
    if (other.isSetAndroid_id()) {
      this.android_id = other.android_id;
    }
    if (other.isSetGaid()) {
      this.gaid = other.gaid;
    }
    if (other.isSetIdfa()) {
      this.idfa = other.idfa;
    }
    if (other.isSetImsi()) {
      this.imsi = other.imsi;
    }
    if (other.isSetImei()) {
      this.imei = other.imei;
    }
    if (other.isSetImei2()) {
      this.imei2 = other.imei2;
    }
    if (other.isSetMac()) {
      this.mac = other.mac;
    }
    if (other.isSetMacsha1()) {
      this.macsha1 = other.macsha1;
    }
    if (other.isSetMacmd5()) {
      this.macmd5 = other.macmd5;
    }
    if (other.isSetUtm_source()) {
      this.utm_source = other.utm_source;
    }
    if (other.isSetUtm_term()) {
      this.utm_term = other.utm_term;
    }
    if (other.isSetUtm_medium()) {
      this.utm_medium = other.utm_medium;
    }
    if (other.isSetUtm_content()) {
      this.utm_content = other.utm_content;
    }
    if (other.isSetUtm_campaign()) {
      this.utm_campaign = other.utm_campaign;
    }
    if (other.isSetExt1()) {
      this.ext1 = other.ext1;
    }
    if (other.isSetExt2()) {
      this.ext2 = other.ext2;
    }
    if (other.isSetExt3()) {
      this.ext3 = other.ext3;
    }
    if (other.isSetExt4()) {
      this.ext4 = other.ext4;
    }
    if (other.isSetExt5()) {
      this.ext5 = other.ext5;
    }
    if (other.isSetInstall_date()) {
      this.install_date = other.install_date;
    }
    if (other.isSetSerial()) {
      this.serial = other.serial;
    }
    this.bid = other.bid;
    if (other.isSetReferrer()) {
      this.referrer = other.referrer;
    }
  }

  public ActivedRequest deepCopy() {
    return new ActivedRequest(this);
  }

  public void clear() {
    this.pub_id = null;
    this.pkgname = null;
    this.region = null;
    this.country = null;
    this.timezone = null;
    this.carrier = null;
    setLongitudeIsSet(false);
    this.longitude = 0.0;
    setLatitudeIsSet(false);
    this.latitude = 0.0;
    setFacebookIsSet(false);
    this.facebook = 0;
    setGpserviceIsSet(false);
    this.gpservice = 0;
    this.language = null;
    this.model = null;
    this.os = null;
    this.os_ver = null;
    this.app_ver = null;
    this.android_id = null;
    this.gaid = null;
    this.idfa = null;
    this.imsi = null;
    this.imei = null;
    this.imei2 = null;
    this.mac = null;
    this.macsha1 = null;
    this.macmd5 = null;
    this.utm_source = null;
    this.utm_term = null;
    this.utm_medium = null;
    this.utm_content = null;
    this.utm_campaign = null;
    this.ext1 = null;
    this.ext2 = null;
    this.ext3 = null;
    this.ext4 = null;
    this.ext5 = null;
    this.install_date = null;
    this.serial = null;
    setBidIsSet(false);
    this.bid = 0;
    this.referrer = null;
  }

  public String getPub_id() {
    return this.pub_id;
  }

  public void setPub_id(String pub_id) {
    this.pub_id = pub_id;
  }

  public void unsetPub_id() {
    this.pub_id = null;
  }

  /** Returns true if field pub_id is set (has been assigned a value) and false otherwise */
  public boolean isSetPub_id() {
    return this.pub_id != null;
  }

  public void setPub_idIsSet(boolean value) {
    if (!value) {
      this.pub_id = null;
    }
  }

  public String getPkgname() {
    return this.pkgname;
  }

  public void setPkgname(String pkgname) {
    this.pkgname = pkgname;
  }

  public void unsetPkgname() {
    this.pkgname = null;
  }

  /** Returns true if field pkgname is set (has been assigned a value) and false otherwise */
  public boolean isSetPkgname() {
    return this.pkgname != null;
  }

  public void setPkgnameIsSet(boolean value) {
    if (!value) {
      this.pkgname = null;
    }
  }

  public String getRegion() {
    return this.region;
  }

  public void setRegion(String region) {
    this.region = region;
  }

  public void unsetRegion() {
    this.region = null;
  }

  /** Returns true if field region is set (has been assigned a value) and false otherwise */
  public boolean isSetRegion() {
    return this.region != null;
  }

  public void setRegionIsSet(boolean value) {
    if (!value) {
      this.region = null;
    }
  }

  public String getCountry() {
    return this.country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public void unsetCountry() {
    this.country = null;
  }

  /** Returns true if field country is set (has been assigned a value) and false otherwise */
  public boolean isSetCountry() {
    return this.country != null;
  }

  public void setCountryIsSet(boolean value) {
    if (!value) {
      this.country = null;
    }
  }

  public String getTimezone() {
    return this.timezone;
  }

  public void setTimezone(String timezone) {
    this.timezone = timezone;
  }

  public void unsetTimezone() {
    this.timezone = null;
  }

  /** Returns true if field timezone is set (has been assigned a value) and false otherwise */
  public boolean isSetTimezone() {
    return this.timezone != null;
  }

  public void setTimezoneIsSet(boolean value) {
    if (!value) {
      this.timezone = null;
    }
  }

  public String getCarrier() {
    return this.carrier;
  }

  public void setCarrier(String carrier) {
    this.carrier = carrier;
  }

  public void unsetCarrier() {
    this.carrier = null;
  }

  /** Returns true if field carrier is set (has been assigned a value) and false otherwise */
  public boolean isSetCarrier() {
    return this.carrier != null;
  }

  public void setCarrierIsSet(boolean value) {
    if (!value) {
      this.carrier = null;
    }
  }

  public double getLongitude() {
    return this.longitude;
  }

  public void setLongitude(double longitude) {
    this.longitude = longitude;
    setLongitudeIsSet(true);
  }

  public void unsetLongitude() {
    __isset_vector[__LONGITUDE_ISSET_ID] = false;
  }

  /** Returns true if field longitude is set (has been assigned a value) and false otherwise */
  public boolean isSetLongitude() {
    return __isset_vector[__LONGITUDE_ISSET_ID];
  }

  public void setLongitudeIsSet(boolean value) {
    __isset_vector[__LONGITUDE_ISSET_ID] = value;
  }

  public double getLatitude() {
    return this.latitude;
  }

  public void setLatitude(double latitude) {
    this.latitude = latitude;
    setLatitudeIsSet(true);
  }

  public void unsetLatitude() {
    __isset_vector[__LATITUDE_ISSET_ID] = false;
  }

  /** Returns true if field latitude is set (has been assigned a value) and false otherwise */
  public boolean isSetLatitude() {
    return __isset_vector[__LATITUDE_ISSET_ID];
  }

  public void setLatitudeIsSet(boolean value) {
    __isset_vector[__LATITUDE_ISSET_ID] = value;
  }

  public int getFacebook() {
    return this.facebook;
  }

  public void setFacebook(int facebook) {
    this.facebook = facebook;
    setFacebookIsSet(true);
  }

  public void unsetFacebook() {
    __isset_vector[__FACEBOOK_ISSET_ID] = false;
  }

  /** Returns true if field facebook is set (has been assigned a value) and false otherwise */
  public boolean isSetFacebook() {
    return __isset_vector[__FACEBOOK_ISSET_ID];
  }

  public void setFacebookIsSet(boolean value) {
    __isset_vector[__FACEBOOK_ISSET_ID] = value;
  }

  public int getGpservice() {
    return this.gpservice;
  }

  public void setGpservice(int gpservice) {
    this.gpservice = gpservice;
    setGpserviceIsSet(true);
  }

  public void unsetGpservice() {
    __isset_vector[__GPSERVICE_ISSET_ID] = false;
  }

  /** Returns true if field gpservice is set (has been assigned a value) and false otherwise */
  public boolean isSetGpservice() {
    return __isset_vector[__GPSERVICE_ISSET_ID];
  }

  public void setGpserviceIsSet(boolean value) {
    __isset_vector[__GPSERVICE_ISSET_ID] = value;
  }

  public String getLanguage() {
    return this.language;
  }

  public void setLanguage(String language) {
    this.language = language;
  }

  public void unsetLanguage() {
    this.language = null;
  }

  /** Returns true if field language is set (has been assigned a value) and false otherwise */
  public boolean isSetLanguage() {
    return this.language != null;
  }

  public void setLanguageIsSet(boolean value) {
    if (!value) {
      this.language = null;
    }
  }

  public String getModel() {
    return this.model;
  }

  public void setModel(String model) {
    this.model = model;
  }

  public void unsetModel() {
    this.model = null;
  }

  /** Returns true if field model is set (has been assigned a value) and false otherwise */
  public boolean isSetModel() {
    return this.model != null;
  }

  public void setModelIsSet(boolean value) {
    if (!value) {
      this.model = null;
    }
  }

  public String getOs() {
    return this.os;
  }

  public void setOs(String os) {
    this.os = os;
  }

  public void unsetOs() {
    this.os = null;
  }

  /** Returns true if field os is set (has been assigned a value) and false otherwise */
  public boolean isSetOs() {
    return this.os != null;
  }

  public void setOsIsSet(boolean value) {
    if (!value) {
      this.os = null;
    }
  }

  public String getOs_ver() {
    return this.os_ver;
  }

  public void setOs_ver(String os_ver) {
    this.os_ver = os_ver;
  }

  public void unsetOs_ver() {
    this.os_ver = null;
  }

  /** Returns true if field os_ver is set (has been assigned a value) and false otherwise */
  public boolean isSetOs_ver() {
    return this.os_ver != null;
  }

  public void setOs_verIsSet(boolean value) {
    if (!value) {
      this.os_ver = null;
    }
  }

  public String getApp_ver() {
    return this.app_ver;
  }

  public void setApp_ver(String app_ver) {
    this.app_ver = app_ver;
  }

  public void unsetApp_ver() {
    this.app_ver = null;
  }

  /** Returns true if field app_ver is set (has been assigned a value) and false otherwise */
  public boolean isSetApp_ver() {
    return this.app_ver != null;
  }

  public void setApp_verIsSet(boolean value) {
    if (!value) {
      this.app_ver = null;
    }
  }

  public String getAndroid_id() {
    return this.android_id;
  }

  public void setAndroid_id(String android_id) {
    this.android_id = android_id;
  }

  public void unsetAndroid_id() {
    this.android_id = null;
  }

  /** Returns true if field android_id is set (has been assigned a value) and false otherwise */
  public boolean isSetAndroid_id() {
    return this.android_id != null;
  }

  public void setAndroid_idIsSet(boolean value) {
    if (!value) {
      this.android_id = null;
    }
  }

  public String getGaid() {
    return this.gaid;
  }

  public void setGaid(String gaid) {
    this.gaid = gaid;
  }

  public void unsetGaid() {
    this.gaid = null;
  }

  /** Returns true if field gaid is set (has been assigned a value) and false otherwise */
  public boolean isSetGaid() {
    return this.gaid != null;
  }

  public void setGaidIsSet(boolean value) {
    if (!value) {
      this.gaid = null;
    }
  }

  public String getIdfa() {
    return this.idfa;
  }

  public void setIdfa(String idfa) {
    this.idfa = idfa;
  }

  public void unsetIdfa() {
    this.idfa = null;
  }

  /** Returns true if field idfa is set (has been assigned a value) and false otherwise */
  public boolean isSetIdfa() {
    return this.idfa != null;
  }

  public void setIdfaIsSet(boolean value) {
    if (!value) {
      this.idfa = null;
    }
  }

  public String getImsi() {
    return this.imsi;
  }

  public void setImsi(String imsi) {
    this.imsi = imsi;
  }

  public void unsetImsi() {
    this.imsi = null;
  }

  /** Returns true if field imsi is set (has been assigned a value) and false otherwise */
  public boolean isSetImsi() {
    return this.imsi != null;
  }

  public void setImsiIsSet(boolean value) {
    if (!value) {
      this.imsi = null;
    }
  }

  public String getImei() {
    return this.imei;
  }

  public void setImei(String imei) {
    this.imei = imei;
  }

  public void unsetImei() {
    this.imei = null;
  }

  /** Returns true if field imei is set (has been assigned a value) and false otherwise */
  public boolean isSetImei() {
    return this.imei != null;
  }

  public void setImeiIsSet(boolean value) {
    if (!value) {
      this.imei = null;
    }
  }

  public String getImei2() {
    return this.imei2;
  }

  public void setImei2(String imei2) {
    this.imei2 = imei2;
  }

  public void unsetImei2() {
    this.imei2 = null;
  }

  /** Returns true if field imei2 is set (has been assigned a value) and false otherwise */
  public boolean isSetImei2() {
    return this.imei2 != null;
  }

  public void setImei2IsSet(boolean value) {
    if (!value) {
      this.imei2 = null;
    }
  }

  public String getMac() {
    return this.mac;
  }

  public void setMac(String mac) {
    this.mac = mac;
  }

  public void unsetMac() {
    this.mac = null;
  }

  /** Returns true if field mac is set (has been assigned a value) and false otherwise */
  public boolean isSetMac() {
    return this.mac != null;
  }

  public void setMacIsSet(boolean value) {
    if (!value) {
      this.mac = null;
    }
  }

  public String getMacsha1() {
    return this.macsha1;
  }

  public void setMacsha1(String macsha1) {
    this.macsha1 = macsha1;
  }

  public void unsetMacsha1() {
    this.macsha1 = null;
  }

  /** Returns true if field macsha1 is set (has been assigned a value) and false otherwise */
  public boolean isSetMacsha1() {
    return this.macsha1 != null;
  }

  public void setMacsha1IsSet(boolean value) {
    if (!value) {
      this.macsha1 = null;
    }
  }

  public String getMacmd5() {
    return this.macmd5;
  }

  public void setMacmd5(String macmd5) {
    this.macmd5 = macmd5;
  }

  public void unsetMacmd5() {
    this.macmd5 = null;
  }

  /** Returns true if field macmd5 is set (has been assigned a value) and false otherwise */
  public boolean isSetMacmd5() {
    return this.macmd5 != null;
  }

  public void setMacmd5IsSet(boolean value) {
    if (!value) {
      this.macmd5 = null;
    }
  }

  public String getUtm_source() {
    return this.utm_source;
  }

  public void setUtm_source(String utm_source) {
    this.utm_source = utm_source;
  }

  public void unsetUtm_source() {
    this.utm_source = null;
  }

  /** Returns true if field utm_source is set (has been assigned a value) and false otherwise */
  public boolean isSetUtm_source() {
    return this.utm_source != null;
  }

  public void setUtm_sourceIsSet(boolean value) {
    if (!value) {
      this.utm_source = null;
    }
  }

  public String getUtm_term() {
    return this.utm_term;
  }

  public void setUtm_term(String utm_term) {
    this.utm_term = utm_term;
  }

  public void unsetUtm_term() {
    this.utm_term = null;
  }

  /** Returns true if field utm_term is set (has been assigned a value) and false otherwise */
  public boolean isSetUtm_term() {
    return this.utm_term != null;
  }

  public void setUtm_termIsSet(boolean value) {
    if (!value) {
      this.utm_term = null;
    }
  }

  public String getUtm_medium() {
    return this.utm_medium;
  }

  public void setUtm_medium(String utm_medium) {
    this.utm_medium = utm_medium;
  }

  public void unsetUtm_medium() {
    this.utm_medium = null;
  }

  /** Returns true if field utm_medium is set (has been assigned a value) and false otherwise */
  public boolean isSetUtm_medium() {
    return this.utm_medium != null;
  }

  public void setUtm_mediumIsSet(boolean value) {
    if (!value) {
      this.utm_medium = null;
    }
  }

  public String getUtm_content() {
    return this.utm_content;
  }

  public void setUtm_content(String utm_content) {
    this.utm_content = utm_content;
  }

  public void unsetUtm_content() {
    this.utm_content = null;
  }

  /** Returns true if field utm_content is set (has been assigned a value) and false otherwise */
  public boolean isSetUtm_content() {
    return this.utm_content != null;
  }

  public void setUtm_contentIsSet(boolean value) {
    if (!value) {
      this.utm_content = null;
    }
  }

  public String getUtm_campaign() {
    return this.utm_campaign;
  }

  public void setUtm_campaign(String utm_campaign) {
    this.utm_campaign = utm_campaign;
  }

  public void unsetUtm_campaign() {
    this.utm_campaign = null;
  }

  /** Returns true if field utm_campaign is set (has been assigned a value) and false otherwise */
  public boolean isSetUtm_campaign() {
    return this.utm_campaign != null;
  }

  public void setUtm_campaignIsSet(boolean value) {
    if (!value) {
      this.utm_campaign = null;
    }
  }

  public String getExt1() {
    return this.ext1;
  }

  public void setExt1(String ext1) {
    this.ext1 = ext1;
  }

  public void unsetExt1() {
    this.ext1 = null;
  }

  /** Returns true if field ext1 is set (has been assigned a value) and false otherwise */
  public boolean isSetExt1() {
    return this.ext1 != null;
  }

  public void setExt1IsSet(boolean value) {
    if (!value) {
      this.ext1 = null;
    }
  }

  public String getExt2() {
    return this.ext2;
  }

  public void setExt2(String ext2) {
    this.ext2 = ext2;
  }

  public void unsetExt2() {
    this.ext2 = null;
  }

  /** Returns true if field ext2 is set (has been assigned a value) and false otherwise */
  public boolean isSetExt2() {
    return this.ext2 != null;
  }

  public void setExt2IsSet(boolean value) {
    if (!value) {
      this.ext2 = null;
    }
  }

  public String getExt3() {
    return this.ext3;
  }

  public void setExt3(String ext3) {
    this.ext3 = ext3;
  }

  public void unsetExt3() {
    this.ext3 = null;
  }

  /** Returns true if field ext3 is set (has been assigned a value) and false otherwise */
  public boolean isSetExt3() {
    return this.ext3 != null;
  }

  public void setExt3IsSet(boolean value) {
    if (!value) {
      this.ext3 = null;
    }
  }

  public String getExt4() {
    return this.ext4;
  }

  public void setExt4(String ext4) {
    this.ext4 = ext4;
  }

  public void unsetExt4() {
    this.ext4 = null;
  }

  /** Returns true if field ext4 is set (has been assigned a value) and false otherwise */
  public boolean isSetExt4() {
    return this.ext4 != null;
  }

  public void setExt4IsSet(boolean value) {
    if (!value) {
      this.ext4 = null;
    }
  }

  public String getExt5() {
    return this.ext5;
  }

  public void setExt5(String ext5) {
    this.ext5 = ext5;
  }

  public void unsetExt5() {
    this.ext5 = null;
  }

  /** Returns true if field ext5 is set (has been assigned a value) and false otherwise */
  public boolean isSetExt5() {
    return this.ext5 != null;
  }

  public void setExt5IsSet(boolean value) {
    if (!value) {
      this.ext5 = null;
    }
  }

  public String getInstall_date() {
    return this.install_date;
  }

  public void setInstall_date(String install_date) {
    this.install_date = install_date;
  }

  public void unsetInstall_date() {
    this.install_date = null;
  }

  /** Returns true if field install_date is set (has been assigned a value) and false otherwise */
  public boolean isSetInstall_date() {
    return this.install_date != null;
  }

  public void setInstall_dateIsSet(boolean value) {
    if (!value) {
      this.install_date = null;
    }
  }

  public String getSerial() {
    return this.serial;
  }

  public void setSerial(String serial) {
    this.serial = serial;
  }

  public void unsetSerial() {
    this.serial = null;
  }

  /** Returns true if field serial is set (has been assigned a value) and false otherwise */
  public boolean isSetSerial() {
    return this.serial != null;
  }

  public void setSerialIsSet(boolean value) {
    if (!value) {
      this.serial = null;
    }
  }

  public int getBid() {
    return this.bid;
  }

  public void setBid(int bid) {
    this.bid = bid;
    setBidIsSet(true);
  }

  public void unsetBid() {
    __isset_vector[__BID_ISSET_ID] = false;
  }

  /** Returns true if field bid is set (has been assigned a value) and false otherwise */
  public boolean isSetBid() {
    return __isset_vector[__BID_ISSET_ID];
  }

  public void setBidIsSet(boolean value) {
    __isset_vector[__BID_ISSET_ID] = value;
  }

  public String getReferrer() {
    return this.referrer;
  }

  public void setReferrer(String referrer) {
    this.referrer = referrer;
  }

  public void unsetReferrer() {
    this.referrer = null;
  }

  /** Returns true if field referrer is set (has been assigned a value) and false otherwise */
  public boolean isSetReferrer() {
    return this.referrer != null;
  }

  public void setReferrerIsSet(boolean value) {
    if (!value) {
      this.referrer = null;
    }
  }

  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ActivedRequest)
      return this.equals((ActivedRequest)that);
    return false;
  }

  public boolean equals(ActivedRequest that) {
    if (that == null)
      return false;

    boolean this_present_pub_id = true && this.isSetPub_id();
    boolean that_present_pub_id = true && that.isSetPub_id();
    if (this_present_pub_id || that_present_pub_id) {
      if (!(this_present_pub_id && that_present_pub_id))
        return false;
      if (!this.pub_id.equals(that.pub_id))
        return false;
    }

    boolean this_present_pkgname = true && this.isSetPkgname();
    boolean that_present_pkgname = true && that.isSetPkgname();
    if (this_present_pkgname || that_present_pkgname) {
      if (!(this_present_pkgname && that_present_pkgname))
        return false;
      if (!this.pkgname.equals(that.pkgname))
        return false;
    }

    boolean this_present_region = true && this.isSetRegion();
    boolean that_present_region = true && that.isSetRegion();
    if (this_present_region || that_present_region) {
      if (!(this_present_region && that_present_region))
        return false;
      if (!this.region.equals(that.region))
        return false;
    }

    boolean this_present_country = true && this.isSetCountry();
    boolean that_present_country = true && that.isSetCountry();
    if (this_present_country || that_present_country) {
      if (!(this_present_country && that_present_country))
        return false;
      if (!this.country.equals(that.country))
        return false;
    }

    boolean this_present_timezone = true && this.isSetTimezone();
    boolean that_present_timezone = true && that.isSetTimezone();
    if (this_present_timezone || that_present_timezone) {
      if (!(this_present_timezone && that_present_timezone))
        return false;
      if (!this.timezone.equals(that.timezone))
        return false;
    }

    boolean this_present_carrier = true && this.isSetCarrier();
    boolean that_present_carrier = true && that.isSetCarrier();
    if (this_present_carrier || that_present_carrier) {
      if (!(this_present_carrier && that_present_carrier))
        return false;
      if (!this.carrier.equals(that.carrier))
        return false;
    }

    boolean this_present_longitude = true;
    boolean that_present_longitude = true;
    if (this_present_longitude || that_present_longitude) {
      if (!(this_present_longitude && that_present_longitude))
        return false;
      if (this.longitude != that.longitude)
        return false;
    }

    boolean this_present_latitude = true;
    boolean that_present_latitude = true;
    if (this_present_latitude || that_present_latitude) {
      if (!(this_present_latitude && that_present_latitude))
        return false;
      if (this.latitude != that.latitude)
        return false;
    }

    boolean this_present_facebook = true;
    boolean that_present_facebook = true;
    if (this_present_facebook || that_present_facebook) {
      if (!(this_present_facebook && that_present_facebook))
        return false;
      if (this.facebook != that.facebook)
        return false;
    }

    boolean this_present_gpservice = true;
    boolean that_present_gpservice = true;
    if (this_present_gpservice || that_present_gpservice) {
      if (!(this_present_gpservice && that_present_gpservice))
        return false;
      if (this.gpservice != that.gpservice)
        return false;
    }

    boolean this_present_language = true && this.isSetLanguage();
    boolean that_present_language = true && that.isSetLanguage();
    if (this_present_language || that_present_language) {
      if (!(this_present_language && that_present_language))
        return false;
      if (!this.language.equals(that.language))
        return false;
    }

    boolean this_present_model = true && this.isSetModel();
    boolean that_present_model = true && that.isSetModel();
    if (this_present_model || that_present_model) {
      if (!(this_present_model && that_present_model))
        return false;
      if (!this.model.equals(that.model))
        return false;
    }

    boolean this_present_os = true && this.isSetOs();
    boolean that_present_os = true && that.isSetOs();
    if (this_present_os || that_present_os) {
      if (!(this_present_os && that_present_os))
        return false;
      if (!this.os.equals(that.os))
        return false;
    }

    boolean this_present_os_ver = true && this.isSetOs_ver();
    boolean that_present_os_ver = true && that.isSetOs_ver();
    if (this_present_os_ver || that_present_os_ver) {
      if (!(this_present_os_ver && that_present_os_ver))
        return false;
      if (!this.os_ver.equals(that.os_ver))
        return false;
    }

    boolean this_present_app_ver = true && this.isSetApp_ver();
    boolean that_present_app_ver = true && that.isSetApp_ver();
    if (this_present_app_ver || that_present_app_ver) {
      if (!(this_present_app_ver && that_present_app_ver))
        return false;
      if (!this.app_ver.equals(that.app_ver))
        return false;
    }

    boolean this_present_android_id = true && this.isSetAndroid_id();
    boolean that_present_android_id = true && that.isSetAndroid_id();
    if (this_present_android_id || that_present_android_id) {
      if (!(this_present_android_id && that_present_android_id))
        return false;
      if (!this.android_id.equals(that.android_id))
        return false;
    }

    boolean this_present_gaid = true && this.isSetGaid();
    boolean that_present_gaid = true && that.isSetGaid();
    if (this_present_gaid || that_present_gaid) {
      if (!(this_present_gaid && that_present_gaid))
        return false;
      if (!this.gaid.equals(that.gaid))
        return false;
    }

    boolean this_present_idfa = true && this.isSetIdfa();
    boolean that_present_idfa = true && that.isSetIdfa();
    if (this_present_idfa || that_present_idfa) {
      if (!(this_present_idfa && that_present_idfa))
        return false;
      if (!this.idfa.equals(that.idfa))
        return false;
    }

    boolean this_present_imsi = true && this.isSetImsi();
    boolean that_present_imsi = true && that.isSetImsi();
    if (this_present_imsi || that_present_imsi) {
      if (!(this_present_imsi && that_present_imsi))
        return false;
      if (!this.imsi.equals(that.imsi))
        return false;
    }

    boolean this_present_imei = true && this.isSetImei();
    boolean that_present_imei = true && that.isSetImei();
    if (this_present_imei || that_present_imei) {
      if (!(this_present_imei && that_present_imei))
        return false;
      if (!this.imei.equals(that.imei))
        return false;
    }

    boolean this_present_imei2 = true && this.isSetImei2();
    boolean that_present_imei2 = true && that.isSetImei2();
    if (this_present_imei2 || that_present_imei2) {
      if (!(this_present_imei2 && that_present_imei2))
        return false;
      if (!this.imei2.equals(that.imei2))
        return false;
    }

    boolean this_present_mac = true && this.isSetMac();
    boolean that_present_mac = true && that.isSetMac();
    if (this_present_mac || that_present_mac) {
      if (!(this_present_mac && that_present_mac))
        return false;
      if (!this.mac.equals(that.mac))
        return false;
    }

    boolean this_present_macsha1 = true && this.isSetMacsha1();
    boolean that_present_macsha1 = true && that.isSetMacsha1();
    if (this_present_macsha1 || that_present_macsha1) {
      if (!(this_present_macsha1 && that_present_macsha1))
        return false;
      if (!this.macsha1.equals(that.macsha1))
        return false;
    }

    boolean this_present_macmd5 = true && this.isSetMacmd5();
    boolean that_present_macmd5 = true && that.isSetMacmd5();
    if (this_present_macmd5 || that_present_macmd5) {
      if (!(this_present_macmd5 && that_present_macmd5))
        return false;
      if (!this.macmd5.equals(that.macmd5))
        return false;
    }

    boolean this_present_utm_source = true && this.isSetUtm_source();
    boolean that_present_utm_source = true && that.isSetUtm_source();
    if (this_present_utm_source || that_present_utm_source) {
      if (!(this_present_utm_source && that_present_utm_source))
        return false;
      if (!this.utm_source.equals(that.utm_source))
        return false;
    }

    boolean this_present_utm_term = true && this.isSetUtm_term();
    boolean that_present_utm_term = true && that.isSetUtm_term();
    if (this_present_utm_term || that_present_utm_term) {
      if (!(this_present_utm_term && that_present_utm_term))
        return false;
      if (!this.utm_term.equals(that.utm_term))
        return false;
    }

    boolean this_present_utm_medium = true && this.isSetUtm_medium();
    boolean that_present_utm_medium = true && that.isSetUtm_medium();
    if (this_present_utm_medium || that_present_utm_medium) {
      if (!(this_present_utm_medium && that_present_utm_medium))
        return false;
      if (!this.utm_medium.equals(that.utm_medium))
        return false;
    }

    boolean this_present_utm_content = true && this.isSetUtm_content();
    boolean that_present_utm_content = true && that.isSetUtm_content();
    if (this_present_utm_content || that_present_utm_content) {
      if (!(this_present_utm_content && that_present_utm_content))
        return false;
      if (!this.utm_content.equals(that.utm_content))
        return false;
    }

    boolean this_present_utm_campaign = true && this.isSetUtm_campaign();
    boolean that_present_utm_campaign = true && that.isSetUtm_campaign();
    if (this_present_utm_campaign || that_present_utm_campaign) {
      if (!(this_present_utm_campaign && that_present_utm_campaign))
        return false;
      if (!this.utm_campaign.equals(that.utm_campaign))
        return false;
    }

    boolean this_present_ext1 = true && this.isSetExt1();
    boolean that_present_ext1 = true && that.isSetExt1();
    if (this_present_ext1 || that_present_ext1) {
      if (!(this_present_ext1 && that_present_ext1))
        return false;
      if (!this.ext1.equals(that.ext1))
        return false;
    }

    boolean this_present_ext2 = true && this.isSetExt2();
    boolean that_present_ext2 = true && that.isSetExt2();
    if (this_present_ext2 || that_present_ext2) {
      if (!(this_present_ext2 && that_present_ext2))
        return false;
      if (!this.ext2.equals(that.ext2))
        return false;
    }

    boolean this_present_ext3 = true && this.isSetExt3();
    boolean that_present_ext3 = true && that.isSetExt3();
    if (this_present_ext3 || that_present_ext3) {
      if (!(this_present_ext3 && that_present_ext3))
        return false;
      if (!this.ext3.equals(that.ext3))
        return false;
    }

    boolean this_present_ext4 = true && this.isSetExt4();
    boolean that_present_ext4 = true && that.isSetExt4();
    if (this_present_ext4 || that_present_ext4) {
      if (!(this_present_ext4 && that_present_ext4))
        return false;
      if (!this.ext4.equals(that.ext4))
        return false;
    }

    boolean this_present_ext5 = true && this.isSetExt5();
    boolean that_present_ext5 = true && that.isSetExt5();
    if (this_present_ext5 || that_present_ext5) {
      if (!(this_present_ext5 && that_present_ext5))
        return false;
      if (!this.ext5.equals(that.ext5))
        return false;
    }

    boolean this_present_install_date = true && this.isSetInstall_date();
    boolean that_present_install_date = true && that.isSetInstall_date();
    if (this_present_install_date || that_present_install_date) {
      if (!(this_present_install_date && that_present_install_date))
        return false;
      if (!this.install_date.equals(that.install_date))
        return false;
    }

    boolean this_present_serial = true && this.isSetSerial();
    boolean that_present_serial = true && that.isSetSerial();
    if (this_present_serial || that_present_serial) {
      if (!(this_present_serial && that_present_serial))
        return false;
      if (!this.serial.equals(that.serial))
        return false;
    }

    boolean this_present_bid = true;
    boolean that_present_bid = true;
    if (this_present_bid || that_present_bid) {
      if (!(this_present_bid && that_present_bid))
        return false;
      if (this.bid != that.bid)
        return false;
    }

    boolean this_present_referrer = true && this.isSetReferrer();
    boolean that_present_referrer = true && that.isSetReferrer();
    if (this_present_referrer || that_present_referrer) {
      if (!(this_present_referrer && that_present_referrer))
        return false;
      if (!this.referrer.equals(that.referrer))
        return false;
    }

    return true;
  }

  public int hashCode() {
    return 0;
  }

  public int compareTo(Object otherObject) {
    if (!getClass().equals(otherObject.getClass())) {
      return getClass().getName().compareTo(otherObject.getClass().getName());
    }

    ActivedRequest other = (ActivedRequest)otherObject;    int lastComparison = 0;

    lastComparison = TBaseHelper.compareTo(isSetPub_id(), other.isSetPub_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPub_id()) {
      lastComparison = TBaseHelper.compareTo(this.pub_id, other.pub_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetPkgname(), other.isSetPkgname());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPkgname()) {
      lastComparison = TBaseHelper.compareTo(this.pkgname, other.pkgname);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetRegion(), other.isSetRegion());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRegion()) {
      lastComparison = TBaseHelper.compareTo(this.region, other.region);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetCountry(), other.isSetCountry());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCountry()) {
      lastComparison = TBaseHelper.compareTo(this.country, other.country);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetTimezone(), other.isSetTimezone());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTimezone()) {
      lastComparison = TBaseHelper.compareTo(this.timezone, other.timezone);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetCarrier(), other.isSetCarrier());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCarrier()) {
      lastComparison = TBaseHelper.compareTo(this.carrier, other.carrier);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetLongitude(), other.isSetLongitude());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLongitude()) {
      lastComparison = TBaseHelper.compareTo(this.longitude, other.longitude);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetLatitude(), other.isSetLatitude());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLatitude()) {
      lastComparison = TBaseHelper.compareTo(this.latitude, other.latitude);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetFacebook(), other.isSetFacebook());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFacebook()) {
      lastComparison = TBaseHelper.compareTo(this.facebook, other.facebook);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetGpservice(), other.isSetGpservice());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGpservice()) {
      lastComparison = TBaseHelper.compareTo(this.gpservice, other.gpservice);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetLanguage(), other.isSetLanguage());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLanguage()) {
      lastComparison = TBaseHelper.compareTo(this.language, other.language);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetModel(), other.isSetModel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetModel()) {
      lastComparison = TBaseHelper.compareTo(this.model, other.model);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetOs(), other.isSetOs());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOs()) {
      lastComparison = TBaseHelper.compareTo(this.os, other.os);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetOs_ver(), other.isSetOs_ver());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOs_ver()) {
      lastComparison = TBaseHelper.compareTo(this.os_ver, other.os_ver);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetApp_ver(), other.isSetApp_ver());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApp_ver()) {
      lastComparison = TBaseHelper.compareTo(this.app_ver, other.app_ver);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetAndroid_id(), other.isSetAndroid_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAndroid_id()) {
      lastComparison = TBaseHelper.compareTo(this.android_id, other.android_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetGaid(), other.isSetGaid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGaid()) {
      lastComparison = TBaseHelper.compareTo(this.gaid, other.gaid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetIdfa(), other.isSetIdfa());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdfa()) {
      lastComparison = TBaseHelper.compareTo(this.idfa, other.idfa);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetImsi(), other.isSetImsi());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImsi()) {
      lastComparison = TBaseHelper.compareTo(this.imsi, other.imsi);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetImei(), other.isSetImei());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImei()) {
      lastComparison = TBaseHelper.compareTo(this.imei, other.imei);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetImei2(), other.isSetImei2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImei2()) {
      lastComparison = TBaseHelper.compareTo(this.imei2, other.imei2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetMac(), other.isSetMac());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMac()) {
      lastComparison = TBaseHelper.compareTo(this.mac, other.mac);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetMacsha1(), other.isSetMacsha1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMacsha1()) {
      lastComparison = TBaseHelper.compareTo(this.macsha1, other.macsha1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetMacmd5(), other.isSetMacmd5());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMacmd5()) {
      lastComparison = TBaseHelper.compareTo(this.macmd5, other.macmd5);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetUtm_source(), other.isSetUtm_source());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUtm_source()) {
      lastComparison = TBaseHelper.compareTo(this.utm_source, other.utm_source);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetUtm_term(), other.isSetUtm_term());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUtm_term()) {
      lastComparison = TBaseHelper.compareTo(this.utm_term, other.utm_term);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetUtm_medium(), other.isSetUtm_medium());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUtm_medium()) {
      lastComparison = TBaseHelper.compareTo(this.utm_medium, other.utm_medium);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetUtm_content(), other.isSetUtm_content());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUtm_content()) {
      lastComparison = TBaseHelper.compareTo(this.utm_content, other.utm_content);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetUtm_campaign(), other.isSetUtm_campaign());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUtm_campaign()) {
      lastComparison = TBaseHelper.compareTo(this.utm_campaign, other.utm_campaign);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetExt1(), other.isSetExt1());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExt1()) {
      lastComparison = TBaseHelper.compareTo(this.ext1, other.ext1);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetExt2(), other.isSetExt2());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExt2()) {
      lastComparison = TBaseHelper.compareTo(this.ext2, other.ext2);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetExt3(), other.isSetExt3());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExt3()) {
      lastComparison = TBaseHelper.compareTo(this.ext3, other.ext3);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetExt4(), other.isSetExt4());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExt4()) {
      lastComparison = TBaseHelper.compareTo(this.ext4, other.ext4);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetExt5(), other.isSetExt5());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExt5()) {
      lastComparison = TBaseHelper.compareTo(this.ext5, other.ext5);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetInstall_date(), other.isSetInstall_date());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetInstall_date()) {
      lastComparison = TBaseHelper.compareTo(this.install_date, other.install_date);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetSerial(), other.isSetSerial());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSerial()) {
      lastComparison = TBaseHelper.compareTo(this.serial, other.serial);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetBid(), other.isSetBid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBid()) {
      lastComparison = TBaseHelper.compareTo(this.bid, other.bid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetReferrer(), other.isSetReferrer());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetReferrer()) {
      lastComparison = TBaseHelper.compareTo(this.referrer, other.referrer);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // PUB_ID
          if (field.type == TType.STRING) {
            this.pub_id = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // PKGNAME
          if (field.type == TType.STRING) {
            this.pkgname = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // REGION
          if (field.type == TType.STRING) {
            this.region = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // COUNTRY
          if (field.type == TType.STRING) {
            this.country = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // TIMEZONE
          if (field.type == TType.STRING) {
            this.timezone = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 6: // CARRIER
          if (field.type == TType.STRING) {
            this.carrier = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 7: // LONGITUDE
          if (field.type == TType.DOUBLE) {
            this.longitude = iprot.readDouble();
            setLongitudeIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 8: // LATITUDE
          if (field.type == TType.DOUBLE) {
            this.latitude = iprot.readDouble();
            setLatitudeIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 9: // FACEBOOK
          if (field.type == TType.I32) {
            this.facebook = iprot.readI32();
            setFacebookIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 10: // GPSERVICE
          if (field.type == TType.I32) {
            this.gpservice = iprot.readI32();
            setGpserviceIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 11: // LANGUAGE
          if (field.type == TType.STRING) {
            this.language = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 12: // MODEL
          if (field.type == TType.STRING) {
            this.model = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 13: // OS
          if (field.type == TType.STRING) {
            this.os = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 14: // OS_VER
          if (field.type == TType.STRING) {
            this.os_ver = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 15: // APP_VER
          if (field.type == TType.STRING) {
            this.app_ver = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 16: // ANDROID_ID
          if (field.type == TType.STRING) {
            this.android_id = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 17: // GAID
          if (field.type == TType.STRING) {
            this.gaid = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 18: // IDFA
          if (field.type == TType.STRING) {
            this.idfa = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 19: // IMSI
          if (field.type == TType.STRING) {
            this.imsi = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 20: // IMEI
          if (field.type == TType.STRING) {
            this.imei = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 21: // IMEI2
          if (field.type == TType.STRING) {
            this.imei2 = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 22: // MAC
          if (field.type == TType.STRING) {
            this.mac = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 23: // MACSHA1
          if (field.type == TType.STRING) {
            this.macsha1 = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 24: // MACMD5
          if (field.type == TType.STRING) {
            this.macmd5 = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 25: // UTM_SOURCE
          if (field.type == TType.STRING) {
            this.utm_source = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 26: // UTM_TERM
          if (field.type == TType.STRING) {
            this.utm_term = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 27: // UTM_MEDIUM
          if (field.type == TType.STRING) {
            this.utm_medium = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 28: // UTM_CONTENT
          if (field.type == TType.STRING) {
            this.utm_content = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 29: // UTM_CAMPAIGN
          if (field.type == TType.STRING) {
            this.utm_campaign = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 30: // EXT1
          if (field.type == TType.STRING) {
            this.ext1 = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 31: // EXT2
          if (field.type == TType.STRING) {
            this.ext2 = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 32: // EXT3
          if (field.type == TType.STRING) {
            this.ext3 = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 33: // EXT4
          if (field.type == TType.STRING) {
            this.ext4 = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 34: // EXT5
          if (field.type == TType.STRING) {
            this.ext5 = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 35: // INSTALL_DATE
          if (field.type == TType.STRING) {
            this.install_date = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 36: // SERIAL
          if (field.type == TType.STRING) {
            this.serial = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 37: // BID
          if (field.type == TType.I32) {
            this.bid = iprot.readI32();
            setBidIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 38: // REFERRER
          if (field.type == TType.STRING) {
            this.referrer = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.pub_id != null) {
      oprot.writeFieldBegin(PUB_ID_FIELD_DESC);
      oprot.writeString(this.pub_id);
      oprot.writeFieldEnd();
    }
    if (this.pkgname != null) {
      oprot.writeFieldBegin(PKGNAME_FIELD_DESC);
      oprot.writeString(this.pkgname);
      oprot.writeFieldEnd();
    }
    if (this.region != null) {
      oprot.writeFieldBegin(REGION_FIELD_DESC);
      oprot.writeString(this.region);
      oprot.writeFieldEnd();
    }
    if (this.country != null) {
      oprot.writeFieldBegin(COUNTRY_FIELD_DESC);
      oprot.writeString(this.country);
      oprot.writeFieldEnd();
    }
    if (this.timezone != null) {
      oprot.writeFieldBegin(TIMEZONE_FIELD_DESC);
      oprot.writeString(this.timezone);
      oprot.writeFieldEnd();
    }
    if (this.carrier != null) {
      oprot.writeFieldBegin(CARRIER_FIELD_DESC);
      oprot.writeString(this.carrier);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(LONGITUDE_FIELD_DESC);
    oprot.writeDouble(this.longitude);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(LATITUDE_FIELD_DESC);
    oprot.writeDouble(this.latitude);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(FACEBOOK_FIELD_DESC);
    oprot.writeI32(this.facebook);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(GPSERVICE_FIELD_DESC);
    oprot.writeI32(this.gpservice);
    oprot.writeFieldEnd();
    if (this.language != null) {
      oprot.writeFieldBegin(LANGUAGE_FIELD_DESC);
      oprot.writeString(this.language);
      oprot.writeFieldEnd();
    }
    if (this.model != null) {
      oprot.writeFieldBegin(MODEL_FIELD_DESC);
      oprot.writeString(this.model);
      oprot.writeFieldEnd();
    }
    if (this.os != null) {
      oprot.writeFieldBegin(OS_FIELD_DESC);
      oprot.writeString(this.os);
      oprot.writeFieldEnd();
    }
    if (this.os_ver != null) {
      oprot.writeFieldBegin(OS_VER_FIELD_DESC);
      oprot.writeString(this.os_ver);
      oprot.writeFieldEnd();
    }
    if (this.app_ver != null) {
      oprot.writeFieldBegin(APP_VER_FIELD_DESC);
      oprot.writeString(this.app_ver);
      oprot.writeFieldEnd();
    }
    if (this.android_id != null) {
      oprot.writeFieldBegin(ANDROID_ID_FIELD_DESC);
      oprot.writeString(this.android_id);
      oprot.writeFieldEnd();
    }
    if (this.gaid != null) {
      oprot.writeFieldBegin(GAID_FIELD_DESC);
      oprot.writeString(this.gaid);
      oprot.writeFieldEnd();
    }
    if (this.idfa != null) {
      oprot.writeFieldBegin(IDFA_FIELD_DESC);
      oprot.writeString(this.idfa);
      oprot.writeFieldEnd();
    }
    if (this.imsi != null) {
      oprot.writeFieldBegin(IMSI_FIELD_DESC);
      oprot.writeString(this.imsi);
      oprot.writeFieldEnd();
    }
    if (this.imei != null) {
      oprot.writeFieldBegin(IMEI_FIELD_DESC);
      oprot.writeString(this.imei);
      oprot.writeFieldEnd();
    }
    if (this.imei2 != null) {
      oprot.writeFieldBegin(IMEI2_FIELD_DESC);
      oprot.writeString(this.imei2);
      oprot.writeFieldEnd();
    }
    if (this.mac != null) {
      oprot.writeFieldBegin(MAC_FIELD_DESC);
      oprot.writeString(this.mac);
      oprot.writeFieldEnd();
    }
    if (this.macsha1 != null) {
      oprot.writeFieldBegin(MACSHA1_FIELD_DESC);
      oprot.writeString(this.macsha1);
      oprot.writeFieldEnd();
    }
    if (this.macmd5 != null) {
      oprot.writeFieldBegin(MACMD5_FIELD_DESC);
      oprot.writeString(this.macmd5);
      oprot.writeFieldEnd();
    }
    if (this.utm_source != null) {
      oprot.writeFieldBegin(UTM_SOURCE_FIELD_DESC);
      oprot.writeString(this.utm_source);
      oprot.writeFieldEnd();
    }
    if (this.utm_term != null) {
      oprot.writeFieldBegin(UTM_TERM_FIELD_DESC);
      oprot.writeString(this.utm_term);
      oprot.writeFieldEnd();
    }
    if (this.utm_medium != null) {
      oprot.writeFieldBegin(UTM_MEDIUM_FIELD_DESC);
      oprot.writeString(this.utm_medium);
      oprot.writeFieldEnd();
    }
    if (this.utm_content != null) {
      oprot.writeFieldBegin(UTM_CONTENT_FIELD_DESC);
      oprot.writeString(this.utm_content);
      oprot.writeFieldEnd();
    }
    if (this.utm_campaign != null) {
      oprot.writeFieldBegin(UTM_CAMPAIGN_FIELD_DESC);
      oprot.writeString(this.utm_campaign);
      oprot.writeFieldEnd();
    }
    if (this.ext1 != null) {
      oprot.writeFieldBegin(EXT1_FIELD_DESC);
      oprot.writeString(this.ext1);
      oprot.writeFieldEnd();
    }
    if (this.ext2 != null) {
      oprot.writeFieldBegin(EXT2_FIELD_DESC);
      oprot.writeString(this.ext2);
      oprot.writeFieldEnd();
    }
    if (this.ext3 != null) {
      oprot.writeFieldBegin(EXT3_FIELD_DESC);
      oprot.writeString(this.ext3);
      oprot.writeFieldEnd();
    }
    if (this.ext4 != null) {
      oprot.writeFieldBegin(EXT4_FIELD_DESC);
      oprot.writeString(this.ext4);
      oprot.writeFieldEnd();
    }
    if (this.ext5 != null) {
      oprot.writeFieldBegin(EXT5_FIELD_DESC);
      oprot.writeString(this.ext5);
      oprot.writeFieldEnd();
    }
    if (this.install_date != null) {
      oprot.writeFieldBegin(INSTALL_DATE_FIELD_DESC);
      oprot.writeString(this.install_date);
      oprot.writeFieldEnd();
    }
    if (this.serial != null) {
      oprot.writeFieldBegin(SERIAL_FIELD_DESC);
      oprot.writeString(this.serial);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(BID_FIELD_DESC);
    oprot.writeI32(this.bid);
    oprot.writeFieldEnd();
    if (this.referrer != null) {
      oprot.writeFieldBegin(REFERRER_FIELD_DESC);
      oprot.writeString(this.referrer);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  public void validate() throws TException {
    // check for required fields
  }

  public void read(JSONObject obj) throws TException {
    validate();

    try {
      if (obj.has(PUB_ID_FIELD_DESC.name())) {
        this.pub_id = obj.optString(PUB_ID_FIELD_DESC.name());
      }
      if (obj.has(PKGNAME_FIELD_DESC.name())) {
        this.pkgname = obj.optString(PKGNAME_FIELD_DESC.name());
      }
      if (obj.has(REGION_FIELD_DESC.name())) {
        this.region = obj.optString(REGION_FIELD_DESC.name());
      }
      if (obj.has(COUNTRY_FIELD_DESC.name())) {
        this.country = obj.optString(COUNTRY_FIELD_DESC.name());
      }
      if (obj.has(TIMEZONE_FIELD_DESC.name())) {
        this.timezone = obj.optString(TIMEZONE_FIELD_DESC.name());
      }
      if (obj.has(CARRIER_FIELD_DESC.name())) {
        this.carrier = obj.optString(CARRIER_FIELD_DESC.name());
      }
      if (obj.has(LONGITUDE_FIELD_DESC.name())) {
        this.longitude = obj.optDouble(LONGITUDE_FIELD_DESC.name());
        setLongitudeIsSet(true);
      }
      if (obj.has(LATITUDE_FIELD_DESC.name())) {
        this.latitude = obj.optDouble(LATITUDE_FIELD_DESC.name());
        setLatitudeIsSet(true);
      }
      if (obj.has(FACEBOOK_FIELD_DESC.name())) {
        this.facebook = obj.optInt(FACEBOOK_FIELD_DESC.name());
        setFacebookIsSet(true);
      }
      if (obj.has(GPSERVICE_FIELD_DESC.name())) {
        this.gpservice = obj.optInt(GPSERVICE_FIELD_DESC.name());
        setGpserviceIsSet(true);
      }
      if (obj.has(LANGUAGE_FIELD_DESC.name())) {
        this.language = obj.optString(LANGUAGE_FIELD_DESC.name());
      }
      if (obj.has(MODEL_FIELD_DESC.name())) {
        this.model = obj.optString(MODEL_FIELD_DESC.name());
      }
      if (obj.has(OS_FIELD_DESC.name())) {
        this.os = obj.optString(OS_FIELD_DESC.name());
      }
      if (obj.has(OS_VER_FIELD_DESC.name())) {
        this.os_ver = obj.optString(OS_VER_FIELD_DESC.name());
      }
      if (obj.has(APP_VER_FIELD_DESC.name())) {
        this.app_ver = obj.optString(APP_VER_FIELD_DESC.name());
      }
      if (obj.has(ANDROID_ID_FIELD_DESC.name())) {
        this.android_id = obj.optString(ANDROID_ID_FIELD_DESC.name());
      }
      if (obj.has(GAID_FIELD_DESC.name())) {
        this.gaid = obj.optString(GAID_FIELD_DESC.name());
      }
      if (obj.has(IDFA_FIELD_DESC.name())) {
        this.idfa = obj.optString(IDFA_FIELD_DESC.name());
      }
      if (obj.has(IMSI_FIELD_DESC.name())) {
        this.imsi = obj.optString(IMSI_FIELD_DESC.name());
      }
      if (obj.has(IMEI_FIELD_DESC.name())) {
        this.imei = obj.optString(IMEI_FIELD_DESC.name());
      }
      if (obj.has(IMEI2_FIELD_DESC.name())) {
        this.imei2 = obj.optString(IMEI2_FIELD_DESC.name());
      }
      if (obj.has(MAC_FIELD_DESC.name())) {
        this.mac = obj.optString(MAC_FIELD_DESC.name());
      }
      if (obj.has(MACSHA1_FIELD_DESC.name())) {
        this.macsha1 = obj.optString(MACSHA1_FIELD_DESC.name());
      }
      if (obj.has(MACMD5_FIELD_DESC.name())) {
        this.macmd5 = obj.optString(MACMD5_FIELD_DESC.name());
      }
      if (obj.has(UTM_SOURCE_FIELD_DESC.name())) {
        this.utm_source = obj.optString(UTM_SOURCE_FIELD_DESC.name());
      }
      if (obj.has(UTM_TERM_FIELD_DESC.name())) {
        this.utm_term = obj.optString(UTM_TERM_FIELD_DESC.name());
      }
      if (obj.has(UTM_MEDIUM_FIELD_DESC.name())) {
        this.utm_medium = obj.optString(UTM_MEDIUM_FIELD_DESC.name());
      }
      if (obj.has(UTM_CONTENT_FIELD_DESC.name())) {
        this.utm_content = obj.optString(UTM_CONTENT_FIELD_DESC.name());
      }
      if (obj.has(UTM_CAMPAIGN_FIELD_DESC.name())) {
        this.utm_campaign = obj.optString(UTM_CAMPAIGN_FIELD_DESC.name());
      }
      if (obj.has(EXT1_FIELD_DESC.name())) {
        this.ext1 = obj.optString(EXT1_FIELD_DESC.name());
      }
      if (obj.has(EXT2_FIELD_DESC.name())) {
        this.ext2 = obj.optString(EXT2_FIELD_DESC.name());
      }
      if (obj.has(EXT3_FIELD_DESC.name())) {
        this.ext3 = obj.optString(EXT3_FIELD_DESC.name());
      }
      if (obj.has(EXT4_FIELD_DESC.name())) {
        this.ext4 = obj.optString(EXT4_FIELD_DESC.name());
      }
      if (obj.has(EXT5_FIELD_DESC.name())) {
        this.ext5 = obj.optString(EXT5_FIELD_DESC.name());
      }
      if (obj.has(INSTALL_DATE_FIELD_DESC.name())) {
        this.install_date = obj.optString(INSTALL_DATE_FIELD_DESC.name());
      }
      if (obj.has(SERIAL_FIELD_DESC.name())) {
        this.serial = obj.optString(SERIAL_FIELD_DESC.name());
      }
      if (obj.has(BID_FIELD_DESC.name())) {
        this.bid = obj.optInt(BID_FIELD_DESC.name());
        setBidIsSet(true);
      }
      if (obj.has(REFERRER_FIELD_DESC.name())) {
        this.referrer = obj.optString(REFERRER_FIELD_DESC.name());
      }
    } catch (Exception e) {
        throw new TException(e);
    }
  }

  public void write(JSONObject obj) throws TException {
    validate();

    try {
      if (this.pub_id != null) {
        Object v_pub_id = this.pub_id;
        obj.put(PUB_ID_FIELD_DESC.name(), v_pub_id);
      }
      if (this.pkgname != null) {
        Object v_pkgname = this.pkgname;
        obj.put(PKGNAME_FIELD_DESC.name(), v_pkgname);
      }
      if (this.region != null) {
        Object v_region = this.region;
        obj.put(REGION_FIELD_DESC.name(), v_region);
      }
      if (this.country != null) {
        Object v_country = this.country;
        obj.put(COUNTRY_FIELD_DESC.name(), v_country);
      }
      if (this.timezone != null) {
        Object v_timezone = this.timezone;
        obj.put(TIMEZONE_FIELD_DESC.name(), v_timezone);
      }
      if (this.carrier != null) {
        Object v_carrier = this.carrier;
        obj.put(CARRIER_FIELD_DESC.name(), v_carrier);
      }
      Object v_longitude = this.longitude;
      obj.put(LONGITUDE_FIELD_DESC.name(), v_longitude);
      Object v_latitude = this.latitude;
      obj.put(LATITUDE_FIELD_DESC.name(), v_latitude);
      Object v_facebook = this.facebook;
      obj.put(FACEBOOK_FIELD_DESC.name(), v_facebook);
      Object v_gpservice = this.gpservice;
      obj.put(GPSERVICE_FIELD_DESC.name(), v_gpservice);
      if (this.language != null) {
        Object v_language = this.language;
        obj.put(LANGUAGE_FIELD_DESC.name(), v_language);
      }
      if (this.model != null) {
        Object v_model = this.model;
        obj.put(MODEL_FIELD_DESC.name(), v_model);
      }
      if (this.os != null) {
        Object v_os = this.os;
        obj.put(OS_FIELD_DESC.name(), v_os);
      }
      if (this.os_ver != null) {
        Object v_os_ver = this.os_ver;
        obj.put(OS_VER_FIELD_DESC.name(), v_os_ver);
      }
      if (this.app_ver != null) {
        Object v_app_ver = this.app_ver;
        obj.put(APP_VER_FIELD_DESC.name(), v_app_ver);
      }
      if (this.android_id != null) {
        Object v_android_id = this.android_id;
        obj.put(ANDROID_ID_FIELD_DESC.name(), v_android_id);
      }
      if (this.gaid != null) {
        Object v_gaid = this.gaid;
        obj.put(GAID_FIELD_DESC.name(), v_gaid);
      }
      if (this.idfa != null) {
        Object v_idfa = this.idfa;
        obj.put(IDFA_FIELD_DESC.name(), v_idfa);
      }
      if (this.imsi != null) {
        Object v_imsi = this.imsi;
        obj.put(IMSI_FIELD_DESC.name(), v_imsi);
      }
      if (this.imei != null) {
        Object v_imei = this.imei;
        obj.put(IMEI_FIELD_DESC.name(), v_imei);
      }
      if (this.imei2 != null) {
        Object v_imei2 = this.imei2;
        obj.put(IMEI2_FIELD_DESC.name(), v_imei2);
      }
      if (this.mac != null) {
        Object v_mac = this.mac;
        obj.put(MAC_FIELD_DESC.name(), v_mac);
      }
      if (this.macsha1 != null) {
        Object v_macsha1 = this.macsha1;
        obj.put(MACSHA1_FIELD_DESC.name(), v_macsha1);
      }
      if (this.macmd5 != null) {
        Object v_macmd5 = this.macmd5;
        obj.put(MACMD5_FIELD_DESC.name(), v_macmd5);
      }
      if (this.utm_source != null) {
        Object v_utm_source = this.utm_source;
        obj.put(UTM_SOURCE_FIELD_DESC.name(), v_utm_source);
      }
      if (this.utm_term != null) {
        Object v_utm_term = this.utm_term;
        obj.put(UTM_TERM_FIELD_DESC.name(), v_utm_term);
      }
      if (this.utm_medium != null) {
        Object v_utm_medium = this.utm_medium;
        obj.put(UTM_MEDIUM_FIELD_DESC.name(), v_utm_medium);
      }
      if (this.utm_content != null) {
        Object v_utm_content = this.utm_content;
        obj.put(UTM_CONTENT_FIELD_DESC.name(), v_utm_content);
      }
      if (this.utm_campaign != null) {
        Object v_utm_campaign = this.utm_campaign;
        obj.put(UTM_CAMPAIGN_FIELD_DESC.name(), v_utm_campaign);
      }
      if (this.ext1 != null) {
        Object v_ext1 = this.ext1;
        obj.put(EXT1_FIELD_DESC.name(), v_ext1);
      }
      if (this.ext2 != null) {
        Object v_ext2 = this.ext2;
        obj.put(EXT2_FIELD_DESC.name(), v_ext2);
      }
      if (this.ext3 != null) {
        Object v_ext3 = this.ext3;
        obj.put(EXT3_FIELD_DESC.name(), v_ext3);
      }
      if (this.ext4 != null) {
        Object v_ext4 = this.ext4;
        obj.put(EXT4_FIELD_DESC.name(), v_ext4);
      }
      if (this.ext5 != null) {
        Object v_ext5 = this.ext5;
        obj.put(EXT5_FIELD_DESC.name(), v_ext5);
      }
      if (this.install_date != null) {
        Object v_install_date = this.install_date;
        obj.put(INSTALL_DATE_FIELD_DESC.name(), v_install_date);
      }
      if (this.serial != null) {
        Object v_serial = this.serial;
        obj.put(SERIAL_FIELD_DESC.name(), v_serial);
      }
      Object v_bid = this.bid;
      obj.put(BID_FIELD_DESC.name(), v_bid);
      if (this.referrer != null) {
        Object v_referrer = this.referrer;
        obj.put(REFERRER_FIELD_DESC.name(), v_referrer);
      }
    } catch (Exception e) {
        throw new TException(e);
    }
  }

}

