/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.solid.analytics.model;

import java.util.Hashtable;
import java.util.Iterator;
import java.util.Vector;
import java.util.Enumeration;

import org.json.*;

import com.solid.analytics.thrift.*;
import com.solid.analytics.thrift.meta_data.*;
import com.solid.analytics.thrift.transport.*;
import com.solid.analytics.thrift.protocol.*;

public class EventRequest implements TBase {
  private static final TStruct STRUCT_DESC = new TStruct("");

  private static final TField UID_FIELD_DESC = new TField("0E70DE63DD91EADD76AE3A85A75C9800", TType.I64, (short)1);
  private static final TField PKGNAME_FIELD_DESC = new TField("247E7A404DC9865E209ABF7FC9736806", TType.STRING, (short)2);
  private static final TField CARRIER_FIELD_DESC = new TField("ABC0A71EBFFC08C3469350E4C6C21FD7", TType.STRING, (short)3);
  private static final TField LONGITUDE_FIELD_DESC = new TField("D5BAE9541F130C2DA32CF601DC64119E", TType.DOUBLE, (short)4);
  private static final TField LATITUDE_FIELD_DESC = new TField("DF466231163DF5342B1B4CE98594D698", TType.DOUBLE, (short)5);
  private static final TField ANDROID_ID_FIELD_DESC = new TField("DAB0432BB529DC1F76C440777C86D232", TType.STRING, (short)6);
  private static final TField GAID_FIELD_DESC = new TField("14A948537488C8020631E254C453125F", TType.STRING, (short)7);
  private static final TField IDFA_FIELD_DESC = new TField("BB30A9CAF941935593088670DDBB2E8F", TType.STRING, (short)8);
  private static final TField IMSI_FIELD_DESC = new TField("3447CA69ECC65C251FF41241E62BBD39", TType.STRING, (short)9);
  private static final TField IMEI_FIELD_DESC = new TField("151D281A624318CDE9DCAAD88E8BB381", TType.STRING, (short)10);
  private static final TField APP_VER_FIELD_DESC = new TField("77CA1148E5F74940EC106A32DC1D5BF5", TType.STRING, (short)11);
  private static final TField SERIAL_FIELD_DESC = new TField("1581BABBFDD04AAF281EEE0DF33200F1", TType.STRING, (short)12);
  private static final TField BID_FIELD_DESC = new TField("ABA758D24BA9012D13123C8970E2DF1B", TType.I32, (short)13);
  private static final TField CATEGORY_FIELD_DESC = new TField("A088104124FBC864F9A717A1D670ADF7", TType.STRING, (short)21);
  private static final TField EVENT_CODE_FIELD_DESC = new TField("4CE17BC1CB9F04609926DF3AEA065024", TType.STRING, (short)22);
  private static final TField LABEL_FIELD_DESC = new TField("A47074F557BF24B278912AB180A02B8B", TType.STRING, (short)23);
  private static final TField VALUE_FIELD_DESC = new TField("DCA77847CD1FE9966C0F581AAE4B956A", TType.STRING, (short)24);
  private static final TField EXTRA_FIELD_DESC = new TField("A0E6EF1779A233086B6274891DCD8050", TType.STRING, (short)25);
  private static final TField CREATED_FIELD_DESC = new TField("A097B36A71479829165AE03FC056B71A", TType.STRING, (short)26);
  private static final TField EVENT_OCCURRED_VER_FIELD_DESC = new TField("68ECB59370E45253FC135ADF5B5FAEC9BE63611BFE7F6A7B958841AFB83E9CE8", TType.I32, (short)27);

  private long uid;
  private String pkgname;
  private String carrier;
  private double longitude;
  private double latitude;
  private String android_id;
  private String gaid;
  private String idfa;
  private String imsi;
  private String imei;
  private String app_ver;
  private String serial;
  private int bid;
  private String category;
  private String event_code;
  private String label;
  private String value;
  private String extra;
  private String created;
  private int event_occurred_ver;

  // isset id assignments
  private static final int __UID_ISSET_ID = 0;
  private static final int __LONGITUDE_ISSET_ID = 1;
  private static final int __LATITUDE_ISSET_ID = 2;
  private static final int __BID_ISSET_ID = 3;
  private static final int __EVENT_OCCURRED_VER_ISSET_ID = 4;
  private boolean[] __isset_vector = new boolean[5];

  public EventRequest() {
  }

  public EventRequest(
    long uid,
    String pkgname,
    String carrier,
    double longitude,
    double latitude,
    String android_id,
    String gaid,
    String idfa,
    String imsi,
    String imei,
    String app_ver,
    String serial,
    int bid,
    String category,
    String event_code,
    String label,
    String value,
    String extra,
    String created,
    int event_occurred_ver)
  {
    this();
    this.uid = uid;
    setUidIsSet(true);
    this.pkgname = pkgname;
    this.carrier = carrier;
    this.longitude = longitude;
    setLongitudeIsSet(true);
    this.latitude = latitude;
    setLatitudeIsSet(true);
    this.android_id = android_id;
    this.gaid = gaid;
    this.idfa = idfa;
    this.imsi = imsi;
    this.imei = imei;
    this.app_ver = app_ver;
    this.serial = serial;
    this.bid = bid;
    setBidIsSet(true);
    this.category = category;
    this.event_code = event_code;
    this.label = label;
    this.value = value;
    this.extra = extra;
    this.created = created;
    this.event_occurred_ver = event_occurred_ver;
    setEvent_occurred_verIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EventRequest(EventRequest other) {
    System.arraycopy(other.__isset_vector, 0, __isset_vector, 0, other.__isset_vector.length);
    this.uid = other.uid;
    if (other.isSetPkgname()) {
      this.pkgname = other.pkgname;
    }
    if (other.isSetCarrier()) {
      this.carrier = other.carrier;
    }
    this.longitude = other.longitude;
    this.latitude = other.latitude;
    if (other.isSetAndroid_id()) {
      this.android_id = other.android_id;
    }
    if (other.isSetGaid()) {
      this.gaid = other.gaid;
    }
    if (other.isSetIdfa()) {
      this.idfa = other.idfa;
    }
    if (other.isSetImsi()) {
      this.imsi = other.imsi;
    }
    if (other.isSetImei()) {
      this.imei = other.imei;
    }
    if (other.isSetApp_ver()) {
      this.app_ver = other.app_ver;
    }
    if (other.isSetSerial()) {
      this.serial = other.serial;
    }
    this.bid = other.bid;
    if (other.isSetCategory()) {
      this.category = other.category;
    }
    if (other.isSetEvent_code()) {
      this.event_code = other.event_code;
    }
    if (other.isSetLabel()) {
      this.label = other.label;
    }
    if (other.isSetValue()) {
      this.value = other.value;
    }
    if (other.isSetExtra()) {
      this.extra = other.extra;
    }
    if (other.isSetCreated()) {
      this.created = other.created;
    }
    this.event_occurred_ver = other.event_occurred_ver;
  }

  public EventRequest deepCopy() {
    return new EventRequest(this);
  }

  public void clear() {
    setUidIsSet(false);
    this.uid = 0;
    this.pkgname = null;
    this.carrier = null;
    setLongitudeIsSet(false);
    this.longitude = 0.0;
    setLatitudeIsSet(false);
    this.latitude = 0.0;
    this.android_id = null;
    this.gaid = null;
    this.idfa = null;
    this.imsi = null;
    this.imei = null;
    this.app_ver = null;
    this.serial = null;
    setBidIsSet(false);
    this.bid = 0;
    this.category = null;
    this.event_code = null;
    this.label = null;
    this.value = null;
    this.extra = null;
    this.created = null;
    setEvent_occurred_verIsSet(false);
    this.event_occurred_ver = 0;
  }

  public long getUid() {
    return this.uid;
  }

  public void setUid(long uid) {
    this.uid = uid;
    setUidIsSet(true);
  }

  public void unsetUid() {
    __isset_vector[__UID_ISSET_ID] = false;
  }

  /** Returns true if field uid is set (has been assigned a value) and false otherwise */
  public boolean isSetUid() {
    return __isset_vector[__UID_ISSET_ID];
  }

  public void setUidIsSet(boolean value) {
    __isset_vector[__UID_ISSET_ID] = value;
  }

  public String getPkgname() {
    return this.pkgname;
  }

  public void setPkgname(String pkgname) {
    this.pkgname = pkgname;
  }

  public void unsetPkgname() {
    this.pkgname = null;
  }

  /** Returns true if field pkgname is set (has been assigned a value) and false otherwise */
  public boolean isSetPkgname() {
    return this.pkgname != null;
  }

  public void setPkgnameIsSet(boolean value) {
    if (!value) {
      this.pkgname = null;
    }
  }

  public String getCarrier() {
    return this.carrier;
  }

  public void setCarrier(String carrier) {
    this.carrier = carrier;
  }

  public void unsetCarrier() {
    this.carrier = null;
  }

  /** Returns true if field carrier is set (has been assigned a value) and false otherwise */
  public boolean isSetCarrier() {
    return this.carrier != null;
  }

  public void setCarrierIsSet(boolean value) {
    if (!value) {
      this.carrier = null;
    }
  }

  public double getLongitude() {
    return this.longitude;
  }

  public void setLongitude(double longitude) {
    this.longitude = longitude;
    setLongitudeIsSet(true);
  }

  public void unsetLongitude() {
    __isset_vector[__LONGITUDE_ISSET_ID] = false;
  }

  /** Returns true if field longitude is set (has been assigned a value) and false otherwise */
  public boolean isSetLongitude() {
    return __isset_vector[__LONGITUDE_ISSET_ID];
  }

  public void setLongitudeIsSet(boolean value) {
    __isset_vector[__LONGITUDE_ISSET_ID] = value;
  }

  public double getLatitude() {
    return this.latitude;
  }

  public void setLatitude(double latitude) {
    this.latitude = latitude;
    setLatitudeIsSet(true);
  }

  public void unsetLatitude() {
    __isset_vector[__LATITUDE_ISSET_ID] = false;
  }

  /** Returns true if field latitude is set (has been assigned a value) and false otherwise */
  public boolean isSetLatitude() {
    return __isset_vector[__LATITUDE_ISSET_ID];
  }

  public void setLatitudeIsSet(boolean value) {
    __isset_vector[__LATITUDE_ISSET_ID] = value;
  }

  public String getAndroid_id() {
    return this.android_id;
  }

  public void setAndroid_id(String android_id) {
    this.android_id = android_id;
  }

  public void unsetAndroid_id() {
    this.android_id = null;
  }

  /** Returns true if field android_id is set (has been assigned a value) and false otherwise */
  public boolean isSetAndroid_id() {
    return this.android_id != null;
  }

  public void setAndroid_idIsSet(boolean value) {
    if (!value) {
      this.android_id = null;
    }
  }

  public String getGaid() {
    return this.gaid;
  }

  public void setGaid(String gaid) {
    this.gaid = gaid;
  }

  public void unsetGaid() {
    this.gaid = null;
  }

  /** Returns true if field gaid is set (has been assigned a value) and false otherwise */
  public boolean isSetGaid() {
    return this.gaid != null;
  }

  public void setGaidIsSet(boolean value) {
    if (!value) {
      this.gaid = null;
    }
  }

  public String getIdfa() {
    return this.idfa;
  }

  public void setIdfa(String idfa) {
    this.idfa = idfa;
  }

  public void unsetIdfa() {
    this.idfa = null;
  }

  /** Returns true if field idfa is set (has been assigned a value) and false otherwise */
  public boolean isSetIdfa() {
    return this.idfa != null;
  }

  public void setIdfaIsSet(boolean value) {
    if (!value) {
      this.idfa = null;
    }
  }

  public String getImsi() {
    return this.imsi;
  }

  public void setImsi(String imsi) {
    this.imsi = imsi;
  }

  public void unsetImsi() {
    this.imsi = null;
  }

  /** Returns true if field imsi is set (has been assigned a value) and false otherwise */
  public boolean isSetImsi() {
    return this.imsi != null;
  }

  public void setImsiIsSet(boolean value) {
    if (!value) {
      this.imsi = null;
    }
  }

  public String getImei() {
    return this.imei;
  }

  public void setImei(String imei) {
    this.imei = imei;
  }

  public void unsetImei() {
    this.imei = null;
  }

  /** Returns true if field imei is set (has been assigned a value) and false otherwise */
  public boolean isSetImei() {
    return this.imei != null;
  }

  public void setImeiIsSet(boolean value) {
    if (!value) {
      this.imei = null;
    }
  }

  public String getApp_ver() {
    return this.app_ver;
  }

  public void setApp_ver(String app_ver) {
    this.app_ver = app_ver;
  }

  public void unsetApp_ver() {
    this.app_ver = null;
  }

  /** Returns true if field app_ver is set (has been assigned a value) and false otherwise */
  public boolean isSetApp_ver() {
    return this.app_ver != null;
  }

  public void setApp_verIsSet(boolean value) {
    if (!value) {
      this.app_ver = null;
    }
  }

  public String getSerial() {
    return this.serial;
  }

  public void setSerial(String serial) {
    this.serial = serial;
  }

  public void unsetSerial() {
    this.serial = null;
  }

  /** Returns true if field serial is set (has been assigned a value) and false otherwise */
  public boolean isSetSerial() {
    return this.serial != null;
  }

  public void setSerialIsSet(boolean value) {
    if (!value) {
      this.serial = null;
    }
  }

  public int getBid() {
    return this.bid;
  }

  public void setBid(int bid) {
    this.bid = bid;
    setBidIsSet(true);
  }

  public void unsetBid() {
    __isset_vector[__BID_ISSET_ID] = false;
  }

  /** Returns true if field bid is set (has been assigned a value) and false otherwise */
  public boolean isSetBid() {
    return __isset_vector[__BID_ISSET_ID];
  }

  public void setBidIsSet(boolean value) {
    __isset_vector[__BID_ISSET_ID] = value;
  }

  public String getCategory() {
    return this.category;
  }

  public void setCategory(String category) {
    this.category = category;
  }

  public void unsetCategory() {
    this.category = null;
  }

  /** Returns true if field category is set (has been assigned a value) and false otherwise */
  public boolean isSetCategory() {
    return this.category != null;
  }

  public void setCategoryIsSet(boolean value) {
    if (!value) {
      this.category = null;
    }
  }

  public String getEvent_code() {
    return this.event_code;
  }

  public void setEvent_code(String event_code) {
    this.event_code = event_code;
  }

  public void unsetEvent_code() {
    this.event_code = null;
  }

  /** Returns true if field event_code is set (has been assigned a value) and false otherwise */
  public boolean isSetEvent_code() {
    return this.event_code != null;
  }

  public void setEvent_codeIsSet(boolean value) {
    if (!value) {
      this.event_code = null;
    }
  }

  public String getLabel() {
    return this.label;
  }

  public void setLabel(String label) {
    this.label = label;
  }

  public void unsetLabel() {
    this.label = null;
  }

  /** Returns true if field label is set (has been assigned a value) and false otherwise */
  public boolean isSetLabel() {
    return this.label != null;
  }

  public void setLabelIsSet(boolean value) {
    if (!value) {
      this.label = null;
    }
  }

  public String getValue() {
    return this.value;
  }

  public void setValue(String value) {
    this.value = value;
  }

  public void unsetValue() {
    this.value = null;
  }

  /** Returns true if field value is set (has been assigned a value) and false otherwise */
  public boolean isSetValue() {
    return this.value != null;
  }

  public void setValueIsSet(boolean value) {
    if (!value) {
      this.value = null;
    }
  }

  public String getExtra() {
    return this.extra;
  }

  public void setExtra(String extra) {
    this.extra = extra;
  }

  public void unsetExtra() {
    this.extra = null;
  }

  /** Returns true if field extra is set (has been assigned a value) and false otherwise */
  public boolean isSetExtra() {
    return this.extra != null;
  }

  public void setExtraIsSet(boolean value) {
    if (!value) {
      this.extra = null;
    }
  }

  public String getCreated() {
    return this.created;
  }

  public void setCreated(String created) {
    this.created = created;
  }

  public void unsetCreated() {
    this.created = null;
  }

  /** Returns true if field created is set (has been assigned a value) and false otherwise */
  public boolean isSetCreated() {
    return this.created != null;
  }

  public void setCreatedIsSet(boolean value) {
    if (!value) {
      this.created = null;
    }
  }

  public int getEvent_occurred_ver() {
    return this.event_occurred_ver;
  }

  public void setEvent_occurred_ver(int event_occurred_ver) {
    this.event_occurred_ver = event_occurred_ver;
    setEvent_occurred_verIsSet(true);
  }

  public void unsetEvent_occurred_ver() {
    __isset_vector[__EVENT_OCCURRED_VER_ISSET_ID] = false;
  }

  /** Returns true if field event_occurred_ver is set (has been assigned a value) and false otherwise */
  public boolean isSetEvent_occurred_ver() {
    return __isset_vector[__EVENT_OCCURRED_VER_ISSET_ID];
  }

  public void setEvent_occurred_verIsSet(boolean value) {
    __isset_vector[__EVENT_OCCURRED_VER_ISSET_ID] = value;
  }

  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EventRequest)
      return this.equals((EventRequest)that);
    return false;
  }

  public boolean equals(EventRequest that) {
    if (that == null)
      return false;

    boolean this_present_uid = true;
    boolean that_present_uid = true;
    if (this_present_uid || that_present_uid) {
      if (!(this_present_uid && that_present_uid))
        return false;
      if (this.uid != that.uid)
        return false;
    }

    boolean this_present_pkgname = true && this.isSetPkgname();
    boolean that_present_pkgname = true && that.isSetPkgname();
    if (this_present_pkgname || that_present_pkgname) {
      if (!(this_present_pkgname && that_present_pkgname))
        return false;
      if (!this.pkgname.equals(that.pkgname))
        return false;
    }

    boolean this_present_carrier = true && this.isSetCarrier();
    boolean that_present_carrier = true && that.isSetCarrier();
    if (this_present_carrier || that_present_carrier) {
      if (!(this_present_carrier && that_present_carrier))
        return false;
      if (!this.carrier.equals(that.carrier))
        return false;
    }

    boolean this_present_longitude = true;
    boolean that_present_longitude = true;
    if (this_present_longitude || that_present_longitude) {
      if (!(this_present_longitude && that_present_longitude))
        return false;
      if (this.longitude != that.longitude)
        return false;
    }

    boolean this_present_latitude = true;
    boolean that_present_latitude = true;
    if (this_present_latitude || that_present_latitude) {
      if (!(this_present_latitude && that_present_latitude))
        return false;
      if (this.latitude != that.latitude)
        return false;
    }

    boolean this_present_android_id = true && this.isSetAndroid_id();
    boolean that_present_android_id = true && that.isSetAndroid_id();
    if (this_present_android_id || that_present_android_id) {
      if (!(this_present_android_id && that_present_android_id))
        return false;
      if (!this.android_id.equals(that.android_id))
        return false;
    }

    boolean this_present_gaid = true && this.isSetGaid();
    boolean that_present_gaid = true && that.isSetGaid();
    if (this_present_gaid || that_present_gaid) {
      if (!(this_present_gaid && that_present_gaid))
        return false;
      if (!this.gaid.equals(that.gaid))
        return false;
    }

    boolean this_present_idfa = true && this.isSetIdfa();
    boolean that_present_idfa = true && that.isSetIdfa();
    if (this_present_idfa || that_present_idfa) {
      if (!(this_present_idfa && that_present_idfa))
        return false;
      if (!this.idfa.equals(that.idfa))
        return false;
    }

    boolean this_present_imsi = true && this.isSetImsi();
    boolean that_present_imsi = true && that.isSetImsi();
    if (this_present_imsi || that_present_imsi) {
      if (!(this_present_imsi && that_present_imsi))
        return false;
      if (!this.imsi.equals(that.imsi))
        return false;
    }

    boolean this_present_imei = true && this.isSetImei();
    boolean that_present_imei = true && that.isSetImei();
    if (this_present_imei || that_present_imei) {
      if (!(this_present_imei && that_present_imei))
        return false;
      if (!this.imei.equals(that.imei))
        return false;
    }

    boolean this_present_app_ver = true && this.isSetApp_ver();
    boolean that_present_app_ver = true && that.isSetApp_ver();
    if (this_present_app_ver || that_present_app_ver) {
      if (!(this_present_app_ver && that_present_app_ver))
        return false;
      if (!this.app_ver.equals(that.app_ver))
        return false;
    }

    boolean this_present_serial = true && this.isSetSerial();
    boolean that_present_serial = true && that.isSetSerial();
    if (this_present_serial || that_present_serial) {
      if (!(this_present_serial && that_present_serial))
        return false;
      if (!this.serial.equals(that.serial))
        return false;
    }

    boolean this_present_bid = true;
    boolean that_present_bid = true;
    if (this_present_bid || that_present_bid) {
      if (!(this_present_bid && that_present_bid))
        return false;
      if (this.bid != that.bid)
        return false;
    }

    boolean this_present_category = true && this.isSetCategory();
    boolean that_present_category = true && that.isSetCategory();
    if (this_present_category || that_present_category) {
      if (!(this_present_category && that_present_category))
        return false;
      if (!this.category.equals(that.category))
        return false;
    }

    boolean this_present_event_code = true && this.isSetEvent_code();
    boolean that_present_event_code = true && that.isSetEvent_code();
    if (this_present_event_code || that_present_event_code) {
      if (!(this_present_event_code && that_present_event_code))
        return false;
      if (!this.event_code.equals(that.event_code))
        return false;
    }

    boolean this_present_label = true && this.isSetLabel();
    boolean that_present_label = true && that.isSetLabel();
    if (this_present_label || that_present_label) {
      if (!(this_present_label && that_present_label))
        return false;
      if (!this.label.equals(that.label))
        return false;
    }

    boolean this_present_value = true && this.isSetValue();
    boolean that_present_value = true && that.isSetValue();
    if (this_present_value || that_present_value) {
      if (!(this_present_value && that_present_value))
        return false;
      if (!this.value.equals(that.value))
        return false;
    }

    boolean this_present_extra = true && this.isSetExtra();
    boolean that_present_extra = true && that.isSetExtra();
    if (this_present_extra || that_present_extra) {
      if (!(this_present_extra && that_present_extra))
        return false;
      if (!this.extra.equals(that.extra))
        return false;
    }

    boolean this_present_created = true && this.isSetCreated();
    boolean that_present_created = true && that.isSetCreated();
    if (this_present_created || that_present_created) {
      if (!(this_present_created && that_present_created))
        return false;
      if (!this.created.equals(that.created))
        return false;
    }

    boolean this_present_event_occurred_ver = true;
    boolean that_present_event_occurred_ver = true;
    if (this_present_event_occurred_ver || that_present_event_occurred_ver) {
      if (!(this_present_event_occurred_ver && that_present_event_occurred_ver))
        return false;
      if (this.event_occurred_ver != that.event_occurred_ver)
        return false;
    }

    return true;
  }

  public int hashCode() {
    return 0;
  }

  public int compareTo(Object otherObject) {
    if (!getClass().equals(otherObject.getClass())) {
      return getClass().getName().compareTo(otherObject.getClass().getName());
    }

    EventRequest other = (EventRequest)otherObject;    int lastComparison = 0;

    lastComparison = TBaseHelper.compareTo(isSetUid(), other.isSetUid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUid()) {
      lastComparison = TBaseHelper.compareTo(this.uid, other.uid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetPkgname(), other.isSetPkgname());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPkgname()) {
      lastComparison = TBaseHelper.compareTo(this.pkgname, other.pkgname);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetCarrier(), other.isSetCarrier());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCarrier()) {
      lastComparison = TBaseHelper.compareTo(this.carrier, other.carrier);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetLongitude(), other.isSetLongitude());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLongitude()) {
      lastComparison = TBaseHelper.compareTo(this.longitude, other.longitude);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetLatitude(), other.isSetLatitude());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLatitude()) {
      lastComparison = TBaseHelper.compareTo(this.latitude, other.latitude);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetAndroid_id(), other.isSetAndroid_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAndroid_id()) {
      lastComparison = TBaseHelper.compareTo(this.android_id, other.android_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetGaid(), other.isSetGaid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGaid()) {
      lastComparison = TBaseHelper.compareTo(this.gaid, other.gaid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetIdfa(), other.isSetIdfa());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdfa()) {
      lastComparison = TBaseHelper.compareTo(this.idfa, other.idfa);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetImsi(), other.isSetImsi());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImsi()) {
      lastComparison = TBaseHelper.compareTo(this.imsi, other.imsi);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetImei(), other.isSetImei());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImei()) {
      lastComparison = TBaseHelper.compareTo(this.imei, other.imei);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetApp_ver(), other.isSetApp_ver());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApp_ver()) {
      lastComparison = TBaseHelper.compareTo(this.app_ver, other.app_ver);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetSerial(), other.isSetSerial());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSerial()) {
      lastComparison = TBaseHelper.compareTo(this.serial, other.serial);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetBid(), other.isSetBid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBid()) {
      lastComparison = TBaseHelper.compareTo(this.bid, other.bid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetCategory(), other.isSetCategory());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCategory()) {
      lastComparison = TBaseHelper.compareTo(this.category, other.category);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetEvent_code(), other.isSetEvent_code());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEvent_code()) {
      lastComparison = TBaseHelper.compareTo(this.event_code, other.event_code);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetLabel(), other.isSetLabel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLabel()) {
      lastComparison = TBaseHelper.compareTo(this.label, other.label);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetValue(), other.isSetValue());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetValue()) {
      lastComparison = TBaseHelper.compareTo(this.value, other.value);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetExtra(), other.isSetExtra());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExtra()) {
      lastComparison = TBaseHelper.compareTo(this.extra, other.extra);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetCreated(), other.isSetCreated());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreated()) {
      lastComparison = TBaseHelper.compareTo(this.created, other.created);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetEvent_occurred_ver(), other.isSetEvent_occurred_ver());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEvent_occurred_ver()) {
      lastComparison = TBaseHelper.compareTo(this.event_occurred_ver, other.event_occurred_ver);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // UID
          if (field.type == TType.I64) {
            this.uid = iprot.readI64();
            setUidIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // PKGNAME
          if (field.type == TType.STRING) {
            this.pkgname = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // CARRIER
          if (field.type == TType.STRING) {
            this.carrier = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // LONGITUDE
          if (field.type == TType.DOUBLE) {
            this.longitude = iprot.readDouble();
            setLongitudeIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // LATITUDE
          if (field.type == TType.DOUBLE) {
            this.latitude = iprot.readDouble();
            setLatitudeIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 6: // ANDROID_ID
          if (field.type == TType.STRING) {
            this.android_id = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 7: // GAID
          if (field.type == TType.STRING) {
            this.gaid = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 8: // IDFA
          if (field.type == TType.STRING) {
            this.idfa = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 9: // IMSI
          if (field.type == TType.STRING) {
            this.imsi = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 10: // IMEI
          if (field.type == TType.STRING) {
            this.imei = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 11: // APP_VER
          if (field.type == TType.STRING) {
            this.app_ver = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 12: // SERIAL
          if (field.type == TType.STRING) {
            this.serial = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 13: // BID
          if (field.type == TType.I32) {
            this.bid = iprot.readI32();
            setBidIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 21: // CATEGORY
          if (field.type == TType.STRING) {
            this.category = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 22: // EVENT_CODE
          if (field.type == TType.STRING) {
            this.event_code = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 23: // LABEL
          if (field.type == TType.STRING) {
            this.label = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 24: // VALUE
          if (field.type == TType.STRING) {
            this.value = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 25: // EXTRA
          if (field.type == TType.STRING) {
            this.extra = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 26: // CREATED
          if (field.type == TType.STRING) {
            this.created = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 27: // EVENT_OCCURRED_VER
          if (field.type == TType.I32) {
            this.event_occurred_ver = iprot.readI32();
            setEvent_occurred_verIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    oprot.writeFieldBegin(UID_FIELD_DESC);
    oprot.writeI64(this.uid);
    oprot.writeFieldEnd();
    if (this.pkgname != null) {
      oprot.writeFieldBegin(PKGNAME_FIELD_DESC);
      oprot.writeString(this.pkgname);
      oprot.writeFieldEnd();
    }
    if (this.carrier != null) {
      oprot.writeFieldBegin(CARRIER_FIELD_DESC);
      oprot.writeString(this.carrier);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(LONGITUDE_FIELD_DESC);
    oprot.writeDouble(this.longitude);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(LATITUDE_FIELD_DESC);
    oprot.writeDouble(this.latitude);
    oprot.writeFieldEnd();
    if (this.android_id != null) {
      oprot.writeFieldBegin(ANDROID_ID_FIELD_DESC);
      oprot.writeString(this.android_id);
      oprot.writeFieldEnd();
    }
    if (this.gaid != null) {
      oprot.writeFieldBegin(GAID_FIELD_DESC);
      oprot.writeString(this.gaid);
      oprot.writeFieldEnd();
    }
    if (this.idfa != null) {
      oprot.writeFieldBegin(IDFA_FIELD_DESC);
      oprot.writeString(this.idfa);
      oprot.writeFieldEnd();
    }
    if (this.imsi != null) {
      oprot.writeFieldBegin(IMSI_FIELD_DESC);
      oprot.writeString(this.imsi);
      oprot.writeFieldEnd();
    }
    if (this.imei != null) {
      oprot.writeFieldBegin(IMEI_FIELD_DESC);
      oprot.writeString(this.imei);
      oprot.writeFieldEnd();
    }
    if (this.app_ver != null) {
      oprot.writeFieldBegin(APP_VER_FIELD_DESC);
      oprot.writeString(this.app_ver);
      oprot.writeFieldEnd();
    }
    if (this.serial != null) {
      oprot.writeFieldBegin(SERIAL_FIELD_DESC);
      oprot.writeString(this.serial);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(BID_FIELD_DESC);
    oprot.writeI32(this.bid);
    oprot.writeFieldEnd();
    if (this.category != null) {
      oprot.writeFieldBegin(CATEGORY_FIELD_DESC);
      oprot.writeString(this.category);
      oprot.writeFieldEnd();
    }
    if (this.event_code != null) {
      oprot.writeFieldBegin(EVENT_CODE_FIELD_DESC);
      oprot.writeString(this.event_code);
      oprot.writeFieldEnd();
    }
    if (this.label != null) {
      oprot.writeFieldBegin(LABEL_FIELD_DESC);
      oprot.writeString(this.label);
      oprot.writeFieldEnd();
    }
    if (this.value != null) {
      oprot.writeFieldBegin(VALUE_FIELD_DESC);
      oprot.writeString(this.value);
      oprot.writeFieldEnd();
    }
    if (this.extra != null) {
      oprot.writeFieldBegin(EXTRA_FIELD_DESC);
      oprot.writeString(this.extra);
      oprot.writeFieldEnd();
    }
    if (this.created != null) {
      oprot.writeFieldBegin(CREATED_FIELD_DESC);
      oprot.writeString(this.created);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(EVENT_OCCURRED_VER_FIELD_DESC);
    oprot.writeI32(this.event_occurred_ver);
    oprot.writeFieldEnd();
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  public void validate() throws TException {
    // check for required fields
  }

  public void read(JSONObject obj) throws TException {
    validate();

    try {
      if (obj.has(UID_FIELD_DESC.name())) {
        this.uid = obj.optLong(UID_FIELD_DESC.name());
        setUidIsSet(true);
      }
      if (obj.has(PKGNAME_FIELD_DESC.name())) {
        this.pkgname = obj.optString(PKGNAME_FIELD_DESC.name());
      }
      if (obj.has(CARRIER_FIELD_DESC.name())) {
        this.carrier = obj.optString(CARRIER_FIELD_DESC.name());
      }
      if (obj.has(LONGITUDE_FIELD_DESC.name())) {
        this.longitude = obj.optDouble(LONGITUDE_FIELD_DESC.name());
        setLongitudeIsSet(true);
      }
      if (obj.has(LATITUDE_FIELD_DESC.name())) {
        this.latitude = obj.optDouble(LATITUDE_FIELD_DESC.name());
        setLatitudeIsSet(true);
      }
      if (obj.has(ANDROID_ID_FIELD_DESC.name())) {
        this.android_id = obj.optString(ANDROID_ID_FIELD_DESC.name());
      }
      if (obj.has(GAID_FIELD_DESC.name())) {
        this.gaid = obj.optString(GAID_FIELD_DESC.name());
      }
      if (obj.has(IDFA_FIELD_DESC.name())) {
        this.idfa = obj.optString(IDFA_FIELD_DESC.name());
      }
      if (obj.has(IMSI_FIELD_DESC.name())) {
        this.imsi = obj.optString(IMSI_FIELD_DESC.name());
      }
      if (obj.has(IMEI_FIELD_DESC.name())) {
        this.imei = obj.optString(IMEI_FIELD_DESC.name());
      }
      if (obj.has(APP_VER_FIELD_DESC.name())) {
        this.app_ver = obj.optString(APP_VER_FIELD_DESC.name());
      }
      if (obj.has(SERIAL_FIELD_DESC.name())) {
        this.serial = obj.optString(SERIAL_FIELD_DESC.name());
      }
      if (obj.has(BID_FIELD_DESC.name())) {
        this.bid = obj.optInt(BID_FIELD_DESC.name());
        setBidIsSet(true);
      }
      if (obj.has(CATEGORY_FIELD_DESC.name())) {
        this.category = obj.optString(CATEGORY_FIELD_DESC.name());
      }
      if (obj.has(EVENT_CODE_FIELD_DESC.name())) {
        this.event_code = obj.optString(EVENT_CODE_FIELD_DESC.name());
      }
      if (obj.has(LABEL_FIELD_DESC.name())) {
        this.label = obj.optString(LABEL_FIELD_DESC.name());
      }
      if (obj.has(VALUE_FIELD_DESC.name())) {
        this.value = obj.optString(VALUE_FIELD_DESC.name());
      }
      if (obj.has(EXTRA_FIELD_DESC.name())) {
        this.extra = obj.optString(EXTRA_FIELD_DESC.name());
      }
      if (obj.has(CREATED_FIELD_DESC.name())) {
        this.created = obj.optString(CREATED_FIELD_DESC.name());
      }
      if (obj.has(EVENT_OCCURRED_VER_FIELD_DESC.name())) {
        this.event_occurred_ver = obj.optInt(EVENT_OCCURRED_VER_FIELD_DESC.name());
        setEvent_occurred_verIsSet(true);
      }
    } catch (Exception e) {
        throw new TException(e);
    }
  }

  public void write(JSONObject obj) throws TException {
    validate();

    try {
      Object v_uid = this.uid;
      obj.put(UID_FIELD_DESC.name(), v_uid);
      if (this.pkgname != null) {
        Object v_pkgname = this.pkgname;
        obj.put(PKGNAME_FIELD_DESC.name(), v_pkgname);
      }
      if (this.carrier != null) {
        Object v_carrier = this.carrier;
        obj.put(CARRIER_FIELD_DESC.name(), v_carrier);
      }
      Object v_longitude = this.longitude;
      obj.put(LONGITUDE_FIELD_DESC.name(), v_longitude);
      Object v_latitude = this.latitude;
      obj.put(LATITUDE_FIELD_DESC.name(), v_latitude);
      if (this.android_id != null) {
        Object v_android_id = this.android_id;
        obj.put(ANDROID_ID_FIELD_DESC.name(), v_android_id);
      }
      if (this.gaid != null) {
        Object v_gaid = this.gaid;
        obj.put(GAID_FIELD_DESC.name(), v_gaid);
      }
      if (this.idfa != null) {
        Object v_idfa = this.idfa;
        obj.put(IDFA_FIELD_DESC.name(), v_idfa);
      }
      if (this.imsi != null) {
        Object v_imsi = this.imsi;
        obj.put(IMSI_FIELD_DESC.name(), v_imsi);
      }
      if (this.imei != null) {
        Object v_imei = this.imei;
        obj.put(IMEI_FIELD_DESC.name(), v_imei);
      }
      if (this.app_ver != null) {
        Object v_app_ver = this.app_ver;
        obj.put(APP_VER_FIELD_DESC.name(), v_app_ver);
      }
      if (this.serial != null) {
        Object v_serial = this.serial;
        obj.put(SERIAL_FIELD_DESC.name(), v_serial);
      }
      Object v_bid = this.bid;
      obj.put(BID_FIELD_DESC.name(), v_bid);
      if (this.category != null) {
        Object v_category = this.category;
        obj.put(CATEGORY_FIELD_DESC.name(), v_category);
      }
      if (this.event_code != null) {
        Object v_event_code = this.event_code;
        obj.put(EVENT_CODE_FIELD_DESC.name(), v_event_code);
      }
      if (this.label != null) {
        Object v_label = this.label;
        obj.put(LABEL_FIELD_DESC.name(), v_label);
      }
      if (this.value != null) {
        Object v_value = this.value;
        obj.put(VALUE_FIELD_DESC.name(), v_value);
      }
      if (this.extra != null) {
        Object v_extra = this.extra;
        obj.put(EXTRA_FIELD_DESC.name(), v_extra);
      }
      if (this.created != null) {
        Object v_created = this.created;
        obj.put(CREATED_FIELD_DESC.name(), v_created);
      }
      Object v_event_occurred_ver = this.event_occurred_ver;
      obj.put(EVENT_OCCURRED_VER_FIELD_DESC.name(), v_event_occurred_ver);
    } catch (Exception e) {
        throw new TException(e);
    }
  }

}

