/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.solid.analytics.model;

import java.util.Hashtable;
import java.util.Iterator;
import java.util.Vector;
import java.util.Enumeration;

import org.json.*;

import com.solid.analytics.thrift.*;
import com.solid.analytics.thrift.meta_data.*;
import com.solid.analytics.thrift.transport.*;
import com.solid.analytics.thrift.protocol.*;

public class EventsRequest implements TBase {
  private static final TStruct STRUCT_DESC = new TStruct("");

  private static final TField UID_FIELD_DESC = new TField("0E70DE63DD91EADD76AE3A85A75C9800", TType.I64, (short)1);
  private static final TField PKGNAME_FIELD_DESC = new TField("247E7A404DC9865E209ABF7FC9736806", TType.STRING, (short)2);
  private static final TField CARRIER_FIELD_DESC = new TField("ABC0A71EBFFC08C3469350E4C6C21FD7", TType.STRING, (short)3);
  private static final TField LONGITUDE_FIELD_DESC = new TField("D5BAE9541F130C2DA32CF601DC64119E", TType.DOUBLE, (short)4);
  private static final TField LATITUDE_FIELD_DESC = new TField("DF466231163DF5342B1B4CE98594D698", TType.DOUBLE, (short)5);
  private static final TField ANDROID_ID_FIELD_DESC = new TField("DAB0432BB529DC1F76C440777C86D232", TType.STRING, (short)6);
  private static final TField GAID_FIELD_DESC = new TField("14A948537488C8020631E254C453125F", TType.STRING, (short)7);
  private static final TField IDFA_FIELD_DESC = new TField("BB30A9CAF941935593088670DDBB2E8F", TType.STRING, (short)8);
  private static final TField IMSI_FIELD_DESC = new TField("3447CA69ECC65C251FF41241E62BBD39", TType.STRING, (short)9);
  private static final TField IMEI_FIELD_DESC = new TField("151D281A624318CDE9DCAAD88E8BB381", TType.STRING, (short)10);
  private static final TField APP_VER_FIELD_DESC = new TField("77CA1148E5F74940EC106A32DC1D5BF5", TType.STRING, (short)11);
  private static final TField SERIAL_FIELD_DESC = new TField("1581BABBFDD04AAF281EEE0DF33200F1", TType.STRING, (short)12);
  private static final TField BID_FIELD_DESC = new TField("ABA758D24BA9012D13123C8970E2DF1B", TType.I32, (short)13);
  private static final TField EVENTS_FIELD_DESC = new TField("B0137CB7F92E9C312DC29924BB8EFD9F", TType.LIST, (short)21);

  private long uid;
  private String pkgname;
  private String carrier;
  private double longitude;
  private double latitude;
  private String android_id;
  private String gaid;
  private String idfa;
  private String imsi;
  private String imei;
  private String app_ver;
  private String serial;
  private int bid;
  private Vector events;

  // isset id assignments
  private static final int __UID_ISSET_ID = 0;
  private static final int __LONGITUDE_ISSET_ID = 1;
  private static final int __LATITUDE_ISSET_ID = 2;
  private static final int __BID_ISSET_ID = 3;
  private boolean[] __isset_vector = new boolean[4];

  public EventsRequest() {
  }

  public EventsRequest(
    long uid,
    String pkgname,
    String carrier,
    double longitude,
    double latitude,
    String android_id,
    String gaid,
    String idfa,
    String imsi,
    String imei,
    String app_ver,
    String serial,
    int bid,
    Vector events)
  {
    this();
    this.uid = uid;
    setUidIsSet(true);
    this.pkgname = pkgname;
    this.carrier = carrier;
    this.longitude = longitude;
    setLongitudeIsSet(true);
    this.latitude = latitude;
    setLatitudeIsSet(true);
    this.android_id = android_id;
    this.gaid = gaid;
    this.idfa = idfa;
    this.imsi = imsi;
    this.imei = imei;
    this.app_ver = app_ver;
    this.serial = serial;
    this.bid = bid;
    setBidIsSet(true);
    this.events = events;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public EventsRequest(EventsRequest other) {
    System.arraycopy(other.__isset_vector, 0, __isset_vector, 0, other.__isset_vector.length);
    this.uid = other.uid;
    if (other.isSetPkgname()) {
      this.pkgname = other.pkgname;
    }
    if (other.isSetCarrier()) {
      this.carrier = other.carrier;
    }
    this.longitude = other.longitude;
    this.latitude = other.latitude;
    if (other.isSetAndroid_id()) {
      this.android_id = other.android_id;
    }
    if (other.isSetGaid()) {
      this.gaid = other.gaid;
    }
    if (other.isSetIdfa()) {
      this.idfa = other.idfa;
    }
    if (other.isSetImsi()) {
      this.imsi = other.imsi;
    }
    if (other.isSetImei()) {
      this.imei = other.imei;
    }
    if (other.isSetApp_ver()) {
      this.app_ver = other.app_ver;
    }
    if (other.isSetSerial()) {
      this.serial = other.serial;
    }
    this.bid = other.bid;
    if (other.isSetEvents()) {
      Vector __this__events = new Vector();
      for (Enumeration other_enum = other.events.elements(); other_enum.hasMoreElements(); ) {
        Event other_element = (Event)other_enum.nextElement();
        __this__events.addElement(new Event(other_element));
      }
      this.events = __this__events;
    }
  }

  public EventsRequest deepCopy() {
    return new EventsRequest(this);
  }

  public void clear() {
    setUidIsSet(false);
    this.uid = 0;
    this.pkgname = null;
    this.carrier = null;
    setLongitudeIsSet(false);
    this.longitude = 0.0;
    setLatitudeIsSet(false);
    this.latitude = 0.0;
    this.android_id = null;
    this.gaid = null;
    this.idfa = null;
    this.imsi = null;
    this.imei = null;
    this.app_ver = null;
    this.serial = null;
    setBidIsSet(false);
    this.bid = 0;
    this.events = null;
  }

  public long getUid() {
    return this.uid;
  }

  public void setUid(long uid) {
    this.uid = uid;
    setUidIsSet(true);
  }

  public void unsetUid() {
    __isset_vector[__UID_ISSET_ID] = false;
  }

  /** Returns true if field uid is set (has been assigned a value) and false otherwise */
  public boolean isSetUid() {
    return __isset_vector[__UID_ISSET_ID];
  }

  public void setUidIsSet(boolean value) {
    __isset_vector[__UID_ISSET_ID] = value;
  }

  public String getPkgname() {
    return this.pkgname;
  }

  public void setPkgname(String pkgname) {
    this.pkgname = pkgname;
  }

  public void unsetPkgname() {
    this.pkgname = null;
  }

  /** Returns true if field pkgname is set (has been assigned a value) and false otherwise */
  public boolean isSetPkgname() {
    return this.pkgname != null;
  }

  public void setPkgnameIsSet(boolean value) {
    if (!value) {
      this.pkgname = null;
    }
  }

  public String getCarrier() {
    return this.carrier;
  }

  public void setCarrier(String carrier) {
    this.carrier = carrier;
  }

  public void unsetCarrier() {
    this.carrier = null;
  }

  /** Returns true if field carrier is set (has been assigned a value) and false otherwise */
  public boolean isSetCarrier() {
    return this.carrier != null;
  }

  public void setCarrierIsSet(boolean value) {
    if (!value) {
      this.carrier = null;
    }
  }

  public double getLongitude() {
    return this.longitude;
  }

  public void setLongitude(double longitude) {
    this.longitude = longitude;
    setLongitudeIsSet(true);
  }

  public void unsetLongitude() {
    __isset_vector[__LONGITUDE_ISSET_ID] = false;
  }

  /** Returns true if field longitude is set (has been assigned a value) and false otherwise */
  public boolean isSetLongitude() {
    return __isset_vector[__LONGITUDE_ISSET_ID];
  }

  public void setLongitudeIsSet(boolean value) {
    __isset_vector[__LONGITUDE_ISSET_ID] = value;
  }

  public double getLatitude() {
    return this.latitude;
  }

  public void setLatitude(double latitude) {
    this.latitude = latitude;
    setLatitudeIsSet(true);
  }

  public void unsetLatitude() {
    __isset_vector[__LATITUDE_ISSET_ID] = false;
  }

  /** Returns true if field latitude is set (has been assigned a value) and false otherwise */
  public boolean isSetLatitude() {
    return __isset_vector[__LATITUDE_ISSET_ID];
  }

  public void setLatitudeIsSet(boolean value) {
    __isset_vector[__LATITUDE_ISSET_ID] = value;
  }

  public String getAndroid_id() {
    return this.android_id;
  }

  public void setAndroid_id(String android_id) {
    this.android_id = android_id;
  }

  public void unsetAndroid_id() {
    this.android_id = null;
  }

  /** Returns true if field android_id is set (has been assigned a value) and false otherwise */
  public boolean isSetAndroid_id() {
    return this.android_id != null;
  }

  public void setAndroid_idIsSet(boolean value) {
    if (!value) {
      this.android_id = null;
    }
  }

  public String getGaid() {
    return this.gaid;
  }

  public void setGaid(String gaid) {
    this.gaid = gaid;
  }

  public void unsetGaid() {
    this.gaid = null;
  }

  /** Returns true if field gaid is set (has been assigned a value) and false otherwise */
  public boolean isSetGaid() {
    return this.gaid != null;
  }

  public void setGaidIsSet(boolean value) {
    if (!value) {
      this.gaid = null;
    }
  }

  public String getIdfa() {
    return this.idfa;
  }

  public void setIdfa(String idfa) {
    this.idfa = idfa;
  }

  public void unsetIdfa() {
    this.idfa = null;
  }

  /** Returns true if field idfa is set (has been assigned a value) and false otherwise */
  public boolean isSetIdfa() {
    return this.idfa != null;
  }

  public void setIdfaIsSet(boolean value) {
    if (!value) {
      this.idfa = null;
    }
  }

  public String getImsi() {
    return this.imsi;
  }

  public void setImsi(String imsi) {
    this.imsi = imsi;
  }

  public void unsetImsi() {
    this.imsi = null;
  }

  /** Returns true if field imsi is set (has been assigned a value) and false otherwise */
  public boolean isSetImsi() {
    return this.imsi != null;
  }

  public void setImsiIsSet(boolean value) {
    if (!value) {
      this.imsi = null;
    }
  }

  public String getImei() {
    return this.imei;
  }

  public void setImei(String imei) {
    this.imei = imei;
  }

  public void unsetImei() {
    this.imei = null;
  }

  /** Returns true if field imei is set (has been assigned a value) and false otherwise */
  public boolean isSetImei() {
    return this.imei != null;
  }

  public void setImeiIsSet(boolean value) {
    if (!value) {
      this.imei = null;
    }
  }

  public String getApp_ver() {
    return this.app_ver;
  }

  public void setApp_ver(String app_ver) {
    this.app_ver = app_ver;
  }

  public void unsetApp_ver() {
    this.app_ver = null;
  }

  /** Returns true if field app_ver is set (has been assigned a value) and false otherwise */
  public boolean isSetApp_ver() {
    return this.app_ver != null;
  }

  public void setApp_verIsSet(boolean value) {
    if (!value) {
      this.app_ver = null;
    }
  }

  public String getSerial() {
    return this.serial;
  }

  public void setSerial(String serial) {
    this.serial = serial;
  }

  public void unsetSerial() {
    this.serial = null;
  }

  /** Returns true if field serial is set (has been assigned a value) and false otherwise */
  public boolean isSetSerial() {
    return this.serial != null;
  }

  public void setSerialIsSet(boolean value) {
    if (!value) {
      this.serial = null;
    }
  }

  public int getBid() {
    return this.bid;
  }

  public void setBid(int bid) {
    this.bid = bid;
    setBidIsSet(true);
  }

  public void unsetBid() {
    __isset_vector[__BID_ISSET_ID] = false;
  }

  /** Returns true if field bid is set (has been assigned a value) and false otherwise */
  public boolean isSetBid() {
    return __isset_vector[__BID_ISSET_ID];
  }

  public void setBidIsSet(boolean value) {
    __isset_vector[__BID_ISSET_ID] = value;
  }

  public int getEventsSize() {
    return (this.events == null) ? 0 : this.events.size();
  }

  public Enumeration getEventsEnumeration() {
    return (this.events == null) ? null : this.events.elements();
  }

  public void addToEvents(Event elem) {
    if (this.events == null) {
      this.events = new Vector();
    }
    this.events.addElement(elem);
  }

  public Vector getEvents() {
    return this.events;
  }

  public void setEvents(Vector events) {
    this.events = events;
  }

  public void unsetEvents() {
    this.events = null;
  }

  /** Returns true if field events is set (has been assigned a value) and false otherwise */
  public boolean isSetEvents() {
    return this.events != null;
  }

  public void setEventsIsSet(boolean value) {
    if (!value) {
      this.events = null;
    }
  }

  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof EventsRequest)
      return this.equals((EventsRequest)that);
    return false;
  }

  public boolean equals(EventsRequest that) {
    if (that == null)
      return false;

    boolean this_present_uid = true;
    boolean that_present_uid = true;
    if (this_present_uid || that_present_uid) {
      if (!(this_present_uid && that_present_uid))
        return false;
      if (this.uid != that.uid)
        return false;
    }

    boolean this_present_pkgname = true && this.isSetPkgname();
    boolean that_present_pkgname = true && that.isSetPkgname();
    if (this_present_pkgname || that_present_pkgname) {
      if (!(this_present_pkgname && that_present_pkgname))
        return false;
      if (!this.pkgname.equals(that.pkgname))
        return false;
    }

    boolean this_present_carrier = true && this.isSetCarrier();
    boolean that_present_carrier = true && that.isSetCarrier();
    if (this_present_carrier || that_present_carrier) {
      if (!(this_present_carrier && that_present_carrier))
        return false;
      if (!this.carrier.equals(that.carrier))
        return false;
    }

    boolean this_present_longitude = true;
    boolean that_present_longitude = true;
    if (this_present_longitude || that_present_longitude) {
      if (!(this_present_longitude && that_present_longitude))
        return false;
      if (this.longitude != that.longitude)
        return false;
    }

    boolean this_present_latitude = true;
    boolean that_present_latitude = true;
    if (this_present_latitude || that_present_latitude) {
      if (!(this_present_latitude && that_present_latitude))
        return false;
      if (this.latitude != that.latitude)
        return false;
    }

    boolean this_present_android_id = true && this.isSetAndroid_id();
    boolean that_present_android_id = true && that.isSetAndroid_id();
    if (this_present_android_id || that_present_android_id) {
      if (!(this_present_android_id && that_present_android_id))
        return false;
      if (!this.android_id.equals(that.android_id))
        return false;
    }

    boolean this_present_gaid = true && this.isSetGaid();
    boolean that_present_gaid = true && that.isSetGaid();
    if (this_present_gaid || that_present_gaid) {
      if (!(this_present_gaid && that_present_gaid))
        return false;
      if (!this.gaid.equals(that.gaid))
        return false;
    }

    boolean this_present_idfa = true && this.isSetIdfa();
    boolean that_present_idfa = true && that.isSetIdfa();
    if (this_present_idfa || that_present_idfa) {
      if (!(this_present_idfa && that_present_idfa))
        return false;
      if (!this.idfa.equals(that.idfa))
        return false;
    }

    boolean this_present_imsi = true && this.isSetImsi();
    boolean that_present_imsi = true && that.isSetImsi();
    if (this_present_imsi || that_present_imsi) {
      if (!(this_present_imsi && that_present_imsi))
        return false;
      if (!this.imsi.equals(that.imsi))
        return false;
    }

    boolean this_present_imei = true && this.isSetImei();
    boolean that_present_imei = true && that.isSetImei();
    if (this_present_imei || that_present_imei) {
      if (!(this_present_imei && that_present_imei))
        return false;
      if (!this.imei.equals(that.imei))
        return false;
    }

    boolean this_present_app_ver = true && this.isSetApp_ver();
    boolean that_present_app_ver = true && that.isSetApp_ver();
    if (this_present_app_ver || that_present_app_ver) {
      if (!(this_present_app_ver && that_present_app_ver))
        return false;
      if (!this.app_ver.equals(that.app_ver))
        return false;
    }

    boolean this_present_serial = true && this.isSetSerial();
    boolean that_present_serial = true && that.isSetSerial();
    if (this_present_serial || that_present_serial) {
      if (!(this_present_serial && that_present_serial))
        return false;
      if (!this.serial.equals(that.serial))
        return false;
    }

    boolean this_present_bid = true;
    boolean that_present_bid = true;
    if (this_present_bid || that_present_bid) {
      if (!(this_present_bid && that_present_bid))
        return false;
      if (this.bid != that.bid)
        return false;
    }

    boolean this_present_events = true && this.isSetEvents();
    boolean that_present_events = true && that.isSetEvents();
    if (this_present_events || that_present_events) {
      if (!(this_present_events && that_present_events))
        return false;
      if (!this.events.equals(that.events))
        return false;
    }

    return true;
  }

  public int hashCode() {
    return 0;
  }

  public int compareTo(Object otherObject) {
    if (!getClass().equals(otherObject.getClass())) {
      return getClass().getName().compareTo(otherObject.getClass().getName());
    }

    EventsRequest other = (EventsRequest)otherObject;    int lastComparison = 0;

    lastComparison = TBaseHelper.compareTo(isSetUid(), other.isSetUid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUid()) {
      lastComparison = TBaseHelper.compareTo(this.uid, other.uid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetPkgname(), other.isSetPkgname());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPkgname()) {
      lastComparison = TBaseHelper.compareTo(this.pkgname, other.pkgname);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetCarrier(), other.isSetCarrier());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCarrier()) {
      lastComparison = TBaseHelper.compareTo(this.carrier, other.carrier);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetLongitude(), other.isSetLongitude());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLongitude()) {
      lastComparison = TBaseHelper.compareTo(this.longitude, other.longitude);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetLatitude(), other.isSetLatitude());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLatitude()) {
      lastComparison = TBaseHelper.compareTo(this.latitude, other.latitude);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetAndroid_id(), other.isSetAndroid_id());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAndroid_id()) {
      lastComparison = TBaseHelper.compareTo(this.android_id, other.android_id);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetGaid(), other.isSetGaid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetGaid()) {
      lastComparison = TBaseHelper.compareTo(this.gaid, other.gaid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetIdfa(), other.isSetIdfa());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdfa()) {
      lastComparison = TBaseHelper.compareTo(this.idfa, other.idfa);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetImsi(), other.isSetImsi());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImsi()) {
      lastComparison = TBaseHelper.compareTo(this.imsi, other.imsi);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetImei(), other.isSetImei());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetImei()) {
      lastComparison = TBaseHelper.compareTo(this.imei, other.imei);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetApp_ver(), other.isSetApp_ver());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetApp_ver()) {
      lastComparison = TBaseHelper.compareTo(this.app_ver, other.app_ver);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetSerial(), other.isSetSerial());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSerial()) {
      lastComparison = TBaseHelper.compareTo(this.serial, other.serial);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetBid(), other.isSetBid());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetBid()) {
      lastComparison = TBaseHelper.compareTo(this.bid, other.bid);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = TBaseHelper.compareTo(isSetEvents(), other.isSetEvents());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEvents()) {
      lastComparison = TBaseHelper.compareTo(this.events, other.events);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // UID
          if (field.type == TType.I64) {
            this.uid = iprot.readI64();
            setUidIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 2: // PKGNAME
          if (field.type == TType.STRING) {
            this.pkgname = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 3: // CARRIER
          if (field.type == TType.STRING) {
            this.carrier = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 4: // LONGITUDE
          if (field.type == TType.DOUBLE) {
            this.longitude = iprot.readDouble();
            setLongitudeIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 5: // LATITUDE
          if (field.type == TType.DOUBLE) {
            this.latitude = iprot.readDouble();
            setLatitudeIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 6: // ANDROID_ID
          if (field.type == TType.STRING) {
            this.android_id = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 7: // GAID
          if (field.type == TType.STRING) {
            this.gaid = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 8: // IDFA
          if (field.type == TType.STRING) {
            this.idfa = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 9: // IMSI
          if (field.type == TType.STRING) {
            this.imsi = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 10: // IMEI
          if (field.type == TType.STRING) {
            this.imei = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 11: // APP_VER
          if (field.type == TType.STRING) {
            this.app_ver = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 12: // SERIAL
          if (field.type == TType.STRING) {
            this.serial = iprot.readString();
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 13: // BID
          if (field.type == TType.I32) {
            this.bid = iprot.readI32();
            setBidIsSet(true);
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        case 21: // EVENTS
          if (field.type == TType.LIST) {
            {
              TList _list0 = iprot.readListBegin();
              this.events = new Vector(_list0.size);
              for (int _i1 = 0; _i1 < _list0.size; ++_i1)
              {
                Event _elem2;
                _elem2 = new Event();
                _elem2.read(iprot);
                this.events.addElement(_elem2);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    oprot.writeFieldBegin(UID_FIELD_DESC);
    oprot.writeI64(this.uid);
    oprot.writeFieldEnd();
    if (this.pkgname != null) {
      oprot.writeFieldBegin(PKGNAME_FIELD_DESC);
      oprot.writeString(this.pkgname);
      oprot.writeFieldEnd();
    }
    if (this.carrier != null) {
      oprot.writeFieldBegin(CARRIER_FIELD_DESC);
      oprot.writeString(this.carrier);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(LONGITUDE_FIELD_DESC);
    oprot.writeDouble(this.longitude);
    oprot.writeFieldEnd();
    oprot.writeFieldBegin(LATITUDE_FIELD_DESC);
    oprot.writeDouble(this.latitude);
    oprot.writeFieldEnd();
    if (this.android_id != null) {
      oprot.writeFieldBegin(ANDROID_ID_FIELD_DESC);
      oprot.writeString(this.android_id);
      oprot.writeFieldEnd();
    }
    if (this.gaid != null) {
      oprot.writeFieldBegin(GAID_FIELD_DESC);
      oprot.writeString(this.gaid);
      oprot.writeFieldEnd();
    }
    if (this.idfa != null) {
      oprot.writeFieldBegin(IDFA_FIELD_DESC);
      oprot.writeString(this.idfa);
      oprot.writeFieldEnd();
    }
    if (this.imsi != null) {
      oprot.writeFieldBegin(IMSI_FIELD_DESC);
      oprot.writeString(this.imsi);
      oprot.writeFieldEnd();
    }
    if (this.imei != null) {
      oprot.writeFieldBegin(IMEI_FIELD_DESC);
      oprot.writeString(this.imei);
      oprot.writeFieldEnd();
    }
    if (this.app_ver != null) {
      oprot.writeFieldBegin(APP_VER_FIELD_DESC);
      oprot.writeString(this.app_ver);
      oprot.writeFieldEnd();
    }
    if (this.serial != null) {
      oprot.writeFieldBegin(SERIAL_FIELD_DESC);
      oprot.writeString(this.serial);
      oprot.writeFieldEnd();
    }
    oprot.writeFieldBegin(BID_FIELD_DESC);
    oprot.writeI32(this.bid);
    oprot.writeFieldEnd();
    if (this.events != null) {
      oprot.writeFieldBegin(EVENTS_FIELD_DESC);
      {
        oprot.writeListBegin(new TList(TType.STRUCT, this.events.size()));
        for (Enumeration _iter3_enum = this.events.elements(); _iter3_enum.hasMoreElements(); )         {
          Event _iter3 = (Event)_iter3_enum.nextElement();
          _iter3.write(oprot);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  public void validate() throws TException {
    // check for required fields
  }

  public void read(JSONObject obj) throws TException {
    validate();

    try {
      if (obj.has(UID_FIELD_DESC.name())) {
        this.uid = obj.optLong(UID_FIELD_DESC.name());
        setUidIsSet(true);
      }
      if (obj.has(PKGNAME_FIELD_DESC.name())) {
        this.pkgname = obj.optString(PKGNAME_FIELD_DESC.name());
      }
      if (obj.has(CARRIER_FIELD_DESC.name())) {
        this.carrier = obj.optString(CARRIER_FIELD_DESC.name());
      }
      if (obj.has(LONGITUDE_FIELD_DESC.name())) {
        this.longitude = obj.optDouble(LONGITUDE_FIELD_DESC.name());
        setLongitudeIsSet(true);
      }
      if (obj.has(LATITUDE_FIELD_DESC.name())) {
        this.latitude = obj.optDouble(LATITUDE_FIELD_DESC.name());
        setLatitudeIsSet(true);
      }
      if (obj.has(ANDROID_ID_FIELD_DESC.name())) {
        this.android_id = obj.optString(ANDROID_ID_FIELD_DESC.name());
      }
      if (obj.has(GAID_FIELD_DESC.name())) {
        this.gaid = obj.optString(GAID_FIELD_DESC.name());
      }
      if (obj.has(IDFA_FIELD_DESC.name())) {
        this.idfa = obj.optString(IDFA_FIELD_DESC.name());
      }
      if (obj.has(IMSI_FIELD_DESC.name())) {
        this.imsi = obj.optString(IMSI_FIELD_DESC.name());
      }
      if (obj.has(IMEI_FIELD_DESC.name())) {
        this.imei = obj.optString(IMEI_FIELD_DESC.name());
      }
      if (obj.has(APP_VER_FIELD_DESC.name())) {
        this.app_ver = obj.optString(APP_VER_FIELD_DESC.name());
      }
      if (obj.has(SERIAL_FIELD_DESC.name())) {
        this.serial = obj.optString(SERIAL_FIELD_DESC.name());
      }
      if (obj.has(BID_FIELD_DESC.name())) {
        this.bid = obj.optInt(BID_FIELD_DESC.name());
        setBidIsSet(true);
      }
      if (obj.has(EVENTS_FIELD_DESC.name())) {
        {
          JSONArray _list4 = obj.optJSONArray(EVENTS_FIELD_DESC.name());
          this.events = new Vector(_list4.length());
          for (int _i6=0; _i6<_list4.length(); _i6++)
          {
            Event _elem9;
            _elem9 = new Event();
            _elem9.read(_list4.optJSONObject(_i6));
            this.events.addElement(_elem9);
          }
        }
      }
    } catch (Exception e) {
        throw new TException(e);
    }
  }

  public void write(JSONObject obj) throws TException {
    validate();

    try {
      Object v_uid = this.uid;
      obj.put(UID_FIELD_DESC.name(), v_uid);
      if (this.pkgname != null) {
        Object v_pkgname = this.pkgname;
        obj.put(PKGNAME_FIELD_DESC.name(), v_pkgname);
      }
      if (this.carrier != null) {
        Object v_carrier = this.carrier;
        obj.put(CARRIER_FIELD_DESC.name(), v_carrier);
      }
      Object v_longitude = this.longitude;
      obj.put(LONGITUDE_FIELD_DESC.name(), v_longitude);
      Object v_latitude = this.latitude;
      obj.put(LATITUDE_FIELD_DESC.name(), v_latitude);
      if (this.android_id != null) {
        Object v_android_id = this.android_id;
        obj.put(ANDROID_ID_FIELD_DESC.name(), v_android_id);
      }
      if (this.gaid != null) {
        Object v_gaid = this.gaid;
        obj.put(GAID_FIELD_DESC.name(), v_gaid);
      }
      if (this.idfa != null) {
        Object v_idfa = this.idfa;
        obj.put(IDFA_FIELD_DESC.name(), v_idfa);
      }
      if (this.imsi != null) {
        Object v_imsi = this.imsi;
        obj.put(IMSI_FIELD_DESC.name(), v_imsi);
      }
      if (this.imei != null) {
        Object v_imei = this.imei;
        obj.put(IMEI_FIELD_DESC.name(), v_imei);
      }
      if (this.app_ver != null) {
        Object v_app_ver = this.app_ver;
        obj.put(APP_VER_FIELD_DESC.name(), v_app_ver);
      }
      if (this.serial != null) {
        Object v_serial = this.serial;
        obj.put(SERIAL_FIELD_DESC.name(), v_serial);
      }
      Object v_bid = this.bid;
      obj.put(BID_FIELD_DESC.name(), v_bid);
      if (this.events != null) {
        JSONArray v_events = new JSONArray();
        for (Enumeration _iter10_enum = this.events.elements(); _iter10_enum.hasMoreElements(); )         {
          Event _iter10 = (Event)_iter10_enum.nextElement();
          Event  _iter10_value = ((Event)_iter10);
          JSONObject _iter10_value_json = new JSONObject();
          _iter10_value.write(_iter10_value_json);
          v_events.put(_iter10_value_json);
        }
        obj.put(EVENTS_FIELD_DESC.name(), v_events);
      }
    } catch (Exception e) {
        throw new TException(e);
    }
  }

}

