/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.solid.analytics.model;

import java.util.Hashtable;
import java.util.Iterator;
import java.util.Vector;
import java.util.Enumeration;

import org.json.*;

import com.solid.analytics.thrift.*;
import com.solid.analytics.thrift.meta_data.*;
import com.solid.analytics.thrift.transport.*;
import com.solid.analytics.thrift.protocol.*;

public class PropertyList implements TBase {
  private static final TStruct STRUCT_DESC = new TStruct("");

  private static final TField PROPERTIES_FIELD_DESC = new TField("5196ED9D6E7A8ABBFBC73062FD534E2F", TType.LIST, (short)1);

  private Vector properties;

  // isset id assignments

  public PropertyList() {
  }

  public PropertyList(
    Vector properties)
  {
    this();
    this.properties = properties;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public PropertyList(PropertyList other) {
    if (other.isSetProperties()) {
      Vector __this__properties = new Vector();
      for (Enumeration other_enum = other.properties.elements(); other_enum.hasMoreElements(); ) {
        Property other_element = (Property)other_enum.nextElement();
        __this__properties.addElement(new Property(other_element));
      }
      this.properties = __this__properties;
    }
  }

  public PropertyList deepCopy() {
    return new PropertyList(this);
  }

  public void clear() {
    this.properties = null;
  }

  public int getPropertiesSize() {
    return (this.properties == null) ? 0 : this.properties.size();
  }

  public Enumeration getPropertiesEnumeration() {
    return (this.properties == null) ? null : this.properties.elements();
  }

  public void addToProperties(Property elem) {
    if (this.properties == null) {
      this.properties = new Vector();
    }
    this.properties.addElement(elem);
  }

  public Vector getProperties() {
    return this.properties;
  }

  public void setProperties(Vector properties) {
    this.properties = properties;
  }

  public void unsetProperties() {
    this.properties = null;
  }

  /** Returns true if field properties is set (has been assigned a value) and false otherwise */
  public boolean isSetProperties() {
    return this.properties != null;
  }

  public void setPropertiesIsSet(boolean value) {
    if (!value) {
      this.properties = null;
    }
  }

  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof PropertyList)
      return this.equals((PropertyList)that);
    return false;
  }

  public boolean equals(PropertyList that) {
    if (that == null)
      return false;

    boolean this_present_properties = true && this.isSetProperties();
    boolean that_present_properties = true && that.isSetProperties();
    if (this_present_properties || that_present_properties) {
      if (!(this_present_properties && that_present_properties))
        return false;
      if (!this.properties.equals(that.properties))
        return false;
    }

    return true;
  }

  public int hashCode() {
    return 0;
  }

  public int compareTo(Object otherObject) {
    if (!getClass().equals(otherObject.getClass())) {
      return getClass().getName().compareTo(otherObject.getClass().getName());
    }

    PropertyList other = (PropertyList)otherObject;    int lastComparison = 0;

    lastComparison = TBaseHelper.compareTo(isSetProperties(), other.isSetProperties());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetProperties()) {
      lastComparison = TBaseHelper.compareTo(this.properties, other.properties);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public void read(TProtocol iprot) throws TException {
    TField field;
    iprot.readStructBegin();
    while (true)
    {
      field = iprot.readFieldBegin();
      if (field.type == TType.STOP) { 
        break;
      }
      switch (field.id) {
        case 1: // PROPERTIES
          if (field.type == TType.LIST) {
            {
              TList _list11 = iprot.readListBegin();
              this.properties = new Vector(_list11.size);
              for (int _i12 = 0; _i12 < _list11.size; ++_i12)
              {
                Property _elem13;
                _elem13 = new Property();
                _elem13.read(iprot);
                this.properties.addElement(_elem13);
              }
              iprot.readListEnd();
            }
          } else { 
            TProtocolUtil.skip(iprot, field.type);
          }
          break;
        default:
          TProtocolUtil.skip(iprot, field.type);
      }
      iprot.readFieldEnd();
    }
    iprot.readStructEnd();
    validate();
  }

  public void write(TProtocol oprot) throws TException {
    validate();

    oprot.writeStructBegin(STRUCT_DESC);
    if (this.properties != null) {
      oprot.writeFieldBegin(PROPERTIES_FIELD_DESC);
      {
        oprot.writeListBegin(new TList(TType.STRUCT, this.properties.size()));
        for (Enumeration _iter14_enum = this.properties.elements(); _iter14_enum.hasMoreElements(); )         {
          Property _iter14 = (Property)_iter14_enum.nextElement();
          _iter14.write(oprot);
        }
        oprot.writeListEnd();
      }
      oprot.writeFieldEnd();
    }
    oprot.writeFieldStop();
    oprot.writeStructEnd();
  }

  public void validate() throws TException {
    // check for required fields
  }

  public void read(JSONObject obj) throws TException {
    validate();

    try {
      if (obj.has(PROPERTIES_FIELD_DESC.name())) {
        {
          JSONArray _list15 = obj.optJSONArray(PROPERTIES_FIELD_DESC.name());
          this.properties = new Vector(_list15.length());
          for (int _i17=0; _i17<_list15.length(); _i17++)
          {
            Property _elem20;
            _elem20 = new Property();
            _elem20.read(_list15.optJSONObject(_i17));
            this.properties.addElement(_elem20);
          }
        }
      }
    } catch (Exception e) {
        throw new TException(e);
    }
  }

  public void write(JSONObject obj) throws TException {
    validate();

    try {
      if (this.properties != null) {
        JSONArray v_properties = new JSONArray();
        for (Enumeration _iter21_enum = this.properties.elements(); _iter21_enum.hasMoreElements(); )         {
          Property _iter21 = (Property)_iter21_enum.nextElement();
          Property  _iter21_value = ((Property)_iter21);
          JSONObject _iter21_value_json = new JSONObject();
          _iter21_value.write(_iter21_value_json);
          v_properties.put(_iter21_value_json);
        }
        obj.put(PROPERTIES_FIELD_DESC.name(), v_properties);
      }
    } catch (Exception e) {
        throw new TException(e);
    }
  }

}

